import { readFileSync, readdirSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const migrationName = readdirSync(resolve(process.cwd(), "supabase/migrations")).find((name) =>
  name.endsWith("_final_rls_schema_hygiene.sql"),
);
if (!migrationName) throw new Error("Final RLS/schema hygiene migration missing");

const migration = readFileSync(resolve(process.cwd(), "supabase/migrations", migrationName), "utf8");

describe("final RLS and schema hygiene", () => {
  it("removes only empty production migration staging data", () => {
    expect(migration).toContain("migration_staging");
    expect(migration).toContain("if v_rows <> 0 then");
    expect(migration).toContain("referenced by a foreign key");
    expect(migration).toContain("drop schema migration_staging cascade");
  });

  it("adds a durable primary key to notice deletion audit history", () => {
    expect(migration).toContain("studio2_notice_deletion_audit");
    expect(migration).toContain("generated by default as identity");
    expect(migration).toContain("primary key (id)");
  });

  it("indexes only the currently material unindexed foreign keys", () => {
    for (const indexName of [
      "contest_entities_country_id_idx",
      "country_hod_edition_claims_country_id_idx",
      "country_hod_edition_claims_edition_id_idx",
      "jury_votes_receiving_country_id_idx",
      "jury_votes_voter_country_id_idx",
      "jury_votes_voter_entity_id_idx",
      "participants_country_id_idx",
      "results_country_id_idx",
      "televote_votes_country_id_idx",
      "voters_contest_entity_id_idx",
      "voters_country_id_idx",
    ]) {
      expect(migration).toContain(indexName);
    }
    expect(migration).toContain("Expected high-volume FK indexes are missing");
  });

  it("preserves exact select unions while splitting FOR ALL write policies", () => {
    expect(migration).toContain("Capture the exact current SELECT union");
    expect(migration).toContain("p.cmd in ('SELECT','ALL')");
    expect(migration).toContain("create policy %I on %I.%I for insert");
    expect(migration).toContain("create policy %I on %I.%I for update");
    expect(migration).toContain("create policy %I on %I.%I for delete");
    expect(migration).toContain("solaris consolidated anon read");
    expect(migration).toContain("solaris consolidated authenticated read");
  });

  it("verifies the targeted tables no longer have overlapping browser SELECT policies", () => {
    expect(migration).toContain("Multiple anon SELECT policies remain");
    expect(migration).toContain("Multiple authenticated SELECT policies remain");
  });
});
