export type SolarisV6MigrationState =
  | "legacy"
  | "dual-read"
  | "canonical-read"
  | "canonical-write"
  | "retired";

export type SolarisV6DomainDefinition = {
  id: string;
  canonicalWriteModel: string;
  canonicalReadProjection: string;
  publicProjection?: string;
  participantProjection?: string;
  organizerProjection?: string;
  commands: readonly string[];
  events: readonly string[];
  tasks: readonly string[];
  legacySources: readonly string[];
  migrationState: SolarisV6MigrationState;
  retirementCriteria: readonly string[];
};

/**
 * Solaris Studio V6 Canonical Domain Registry.
 *
 * This is deliberately product-facing rather than an ORM catalogue. Each row
 * answers one question: which domain is allowed to define truth for this
 * concept? Physical tables may still contain drafts, snapshots, history or
 * delivery projections, but they are not allowed to become competing product
 * authorities.
 */
export const SOLARIS_V6_DOMAINS: readonly SolarisV6DomainDefinition[] = [
  {
    id: "edition",
    canonicalWriteModel: "edition lifecycle + authoritative edition operation commands",
    canonicalReadProjection: "edition read model",
    publicProjection: "public edition routes",
    participantProjection: "participant edition context",
    organizerProjection: "Organizer edition workspace",
    commands: ["edition.transition", "edition.update", "edition.allocate"],
    events: ["edition.changed", "edition.transitioned"],
    tasks: ["edition.blocker"],
    legacySources: ["browser-global selected edition", "legacy direct edition mutations"],
    migrationState: "canonical-write",
    retirementCriteria: ["No operational route derives edition identity from browser-global state."],
  },
  {
    id: "delegation",
    canonicalWriteModel: "delegation/country-account ownership domain",
    canonicalReadProjection: "delegation readiness projection",
    publicProjection: "country profile",
    participantProjection: "MySolaris delegation workspace",
    organizerProjection: "Organizer delegation workspace",
    commands: ["delegation.assign", "delegation.suspend", "delegation.restore"],
    events: ["delegation.changed"],
    tasks: ["delegation.attention"],
    legacySources: ["legacy HOD role inference", "unscoped country ownership checks"],
    migrationState: "canonical-read",
    retirementCriteria: ["All ownership and editing rights are derived from canonical account/capability state."],
  },
  {
    id: "participation",
    canonicalWriteModel: "edition + delegation participation requirement",
    canonicalReadProjection: "participant readiness projection",
    participantProjection: "MySolaris tasks/readiness",
    organizerProjection: "Participant View + delegation readiness",
    commands: ["participation.override"],
    events: ["participation.changed"],
    tasks: ["participation.blocker"],
    legacySources: ["independent UI readiness aggregators"],
    migrationState: "canonical-read",
    retirementCriteria: ["Home, Tasks, Participant View and readiness consume the same projection."],
  },
  {
    id: "confirmation",
    canonicalWriteModel: "confirmation requirement + versioned submission windows",
    canonicalReadProjection: "canonical confirmations runtime",
    participantProjection: "confirmation flow",
    organizerProjection: "Organizer Confirmations",
    commands: ["confirmation.submit", "confirmation.open", "confirmation.close", "confirmation.grant_edit"],
    events: ["confirmation.submitted", "confirmation.window_changed"],
    tasks: ["confirmation.missing", "confirmation.sync_failed"],
    legacySources: ["legacy confirmations service authority"],
    migrationState: "canonical-write",
    retirementCriteria: ["Later rounds cannot recreate an already-satisfied participation requirement."],
  },
  {
    id: "entry",
    canonicalWriteModel: "versioned entry/submission domain",
    canonicalReadProjection: "entry readiness + published entry projection",
    publicProjection: "public entry",
    participantProjection: "MySolaris entry",
    organizerProjection: "Organizer entry review",
    commands: ["entry.submit", "entry.review", "entry.restore_version"],
    events: ["entry.submitted", "entry.reviewed", "entry.version_changed"],
    tasks: ["entry.incomplete", "entry.review_required"],
    legacySources: ["unversioned direct entry edits"],
    migrationState: "canonical-read",
    retirementCriteria: ["All approvals bind to an exact immutable submitted version."],
  },
  {
    id: "national-selection",
    canonicalWriteModel: "selection review + accepted candidate/winner state",
    canonicalReadProjection: "selection review projection",
    publicProjection: "national final/public selection",
    participantProjection: "selection submission",
    organizerProjection: "Organizer Selection & Entry Review",
    commands: ["selection.review", "selection.select_winner", "selection.clear_winner"],
    events: ["selection.reviewed", "selection.winner_changed"],
    tasks: ["selection.review_required"],
    legacySources: ["client-side winner assignment"],
    migrationState: "canonical-write",
    retirementCriteria: ["Winner assignment only accepts the current valid accepted candidate version."],
  },
  {
    id: "jury",
    canonicalWriteModel: "jury window + ballot lifecycle",
    canonicalReadProjection: "jury operational readiness",
    participantProjection: "jury ballot",
    organizerProjection: "Organizer Jury",
    commands: ["jury.open", "jury.close", "jury.ballot_review", "jury.dnv"],
    events: ["jury.opened", "jury.closed", "jury.ballot_changed"],
    tasks: ["jury.ballot_missing", "jury.review_required"],
    legacySources: ["direct ballot lifecycle mutation"],
    migrationState: "canonical-write",
    retirementCriteria: ["Only canonical valid ballot evidence contributes to result readiness."],
  },
  {
    id: "televote",
    canonicalWriteModel: "televote round state machine",
    canonicalReadProjection: "televote operational projection",
    participantProjection: "televote ballot",
    organizerProjection: "Organizer Televote",
    commands: ["televote.open", "televote.close", "televote.submit"],
    events: ["televote.opened", "televote.closed", "televote.ballot_submitted"],
    tasks: ["televote.missing", "televote.integrity_review"],
    legacySources: ["client-clock eligibility", "direct round state writes"],
    migrationState: "canonical-write",
    retirementCriteria: ["Server time and server transition validation exclusively determine ballot acceptance."],
  },
  {
    id: "results",
    canonicalWriteModel: "versioned result lifecycle operations",
    canonicalReadProjection: "canonical result version/status projection",
    publicProjection: "published results",
    organizerProjection: "Organizer Results",
    commands: ["results.calculate", "results.verify", "results.lock", "results.unlock"],
    events: ["results.calculated", "results.verified", "results.locked"],
    tasks: ["results.blocked"],
    legacySources: ["screen-specific result status interpretation"],
    migrationState: "canonical-write",
    retirementCriteria: ["Every surface derives status from one exact result version."],
  },
  {
    id: "publication",
    canonicalWriteModel: "version-bound publication lifecycle",
    canonicalReadProjection: "publication layer projection",
    publicProjection: "public published surfaces",
    organizerProjection: "Organizer Publish",
    commands: ["publication.schedule", "publication.publish", "publication.hide"],
    events: ["publication.changed", "publication.failed"],
    tasks: ["publication.failed"],
    legacySources: ["implicit publication from calculated state"],
    migrationState: "canonical-write",
    retirementCriteria: ["Publication always binds to exact edition/object/result versions."],
  },
  {
    id: "notice",
    canonicalWriteModel: "versioned official communication",
    canonicalReadProjection: "recipient notice projection",
    publicProjection: "public announcement surfaces",
    participantProjection: "participant Inbox/Home",
    organizerProjection: "Organizer Communications",
    commands: ["notice.publish", "notice.schedule"],
    events: ["notice.published", "notice.superseded"],
    tasks: ["notice.delivery_failed"],
    legacySources: ["independent push-only notices"],
    migrationState: "canonical-read",
    retirementCriteria: ["One notice version projects consistently to every delivery surface."],
  },
  {
    id: "acknowledgement",
    canonicalWriteModel: "notice-version + recipient acknowledgement receipt",
    canonicalReadProjection: "acknowledgement status projection",
    participantProjection: "participant notice acknowledgement",
    organizerProjection: "Organizer acknowledgement tracking",
    commands: ["acknowledgement.record"],
    events: ["acknowledgement.recorded"],
    tasks: ["acknowledgement.required"],
    legacySources: ["read/unread state treated as acknowledgement"],
    migrationState: "canonical-write",
    retirementCriteria: ["Material notice changes can never inherit acknowledgement from an older version."],
  },
  {
    id: "task",
    canonicalWriteModel: "domain-derived Organizer/participant Task Engine",
    canonicalReadProjection: "task projection filtered by audience/capability",
    participantProjection: "MySolaris Tasks",
    organizerProjection: "Organizer Tasks",
    commands: ["task.assign", "task.resolve_manual"],
    events: ["task.opened", "task.resolved"],
    tasks: [],
    legacySources: ["Action Center truth", "Inbox-as-task-state", "UI-local blocker calculations"],
    migrationState: "canonical-write",
    retirementCriteria: ["Every domain-backed task resolves from canonical domain truth."],
  },
  {
    id: "country-identity",
    canonicalWriteModel: "canonical country identity + edition-scoped historical identity",
    canonicalReadProjection: "country identity projection",
    publicProjection: "country/Wiki/results identity",
    participantProjection: "MySolaris country",
    organizerProjection: "Organizer Country",
    commands: ["country.update_identity"],
    events: ["country.identity_changed"],
    tasks: [],
    legacySources: ["feature-local flag/name copies"],
    migrationState: "canonical-read",
    retirementCriteria: ["No voting identity is inferred from historical presentation labels."],
  },
  {
    id: "country-profile",
    canonicalWriteModel: "versioned country profile/design domain",
    canonicalReadProjection: "published country profile",
    publicProjection: "Country/Wiki",
    participantProjection: "MySolaris page builder",
    organizerProjection: "Organizer Public Profile/Appearance",
    commands: ["country_profile.publish", "country_profile.hide", "country_profile.restore"],
    events: ["country_profile.changed"],
    tasks: ["country_profile.moderation"],
    legacySources: ["query-parameter-only organizer override"],
    migrationState: "canonical-read",
    retirementCriteria: ["Organizer support and moderation are explicit, audited surfaces."],
  },
  {
    id: "media",
    canonicalWriteModel: "authorized quarantine + verified media asset lifecycle",
    canonicalReadProjection: "approved media asset projection",
    publicProjection: "processed public assets",
    participantProjection: "upload/review status",
    organizerProjection: "Organizer Media",
    commands: ["media.prepare_upload", "media.finalize_upload", "media.review"],
    events: ["media.verified", "media.reviewed"],
    tasks: ["media.review_required", "media.processing_failed"],
    legacySources: ["direct client bucket writes"],
    migrationState: "canonical-write",
    retirementCriteria: ["All user uploads enter the shared quarantine/verification pipeline."],
  },
  {
    id: "rules",
    canonicalWriteModel: "versioned rule release + interpretation domain",
    canonicalReadProjection: "effective rule projection",
    publicProjection: "Rules",
    participantProjection: "contextual rule guidance",
    organizerProjection: "Rules Manager",
    commands: ["rules.publish", "rules.interpret"],
    events: ["rules.published", "rules.interpreted"],
    tasks: ["rules.compatibility_blocker"],
    legacySources: ["hard-coded derived rule copy"],
    migrationState: "canonical-read",
    retirementCriteria: ["Derived tooling validates compatibility before a rule release becomes authoritative."],
  },
  {
    id: "integrity",
    canonicalWriteModel: "governed cases/evidence/appeal domain",
    canonicalReadProjection: "capability-scoped integrity projection",
    participantProjection: "report/appeal surfaces",
    organizerProjection: "Trust & Governance",
    commands: ["integrity.case_transition", "integrity.appeal_decide", "integrity.identity_reveal"],
    events: ["integrity.case_changed", "integrity.appeal_changed"],
    tasks: ["integrity.review_required"],
    legacySources: ["ungoverned evidence reads"],
    migrationState: "canonical-read",
    retirementCriteria: ["Protected reads and consequential decisions are capability-scoped and auditable."],
  },
  {
    id: "permissions",
    canonicalWriteModel: "capability grants + server-authoritative permission commands",
    canonicalReadProjection: "effective capability projection",
    participantProjection: "available participant actions",
    organizerProjection: "People & Access",
    commands: ["permissions.grant", "permissions.revoke", "permissions.approve_r3"],
    events: ["permissions.changed"],
    tasks: ["permissions.approval_required"],
    legacySources: ["client role checks", "user-editable authorization metadata"],
    migrationState: "canonical-write",
    retirementCriteria: ["Domain code checks trusted capabilities rather than scattered role literals."],
  },
  {
    id: "live-show",
    canonicalWriteModel: "show/rundown/reveal canonical operation state",
    canonicalReadProjection: "live show projection",
    publicProjection: "Show Mode",
    organizerProjection: "Live Operations + Reveal Director",
    commands: ["show.transition", "show.cue", "show.hold"],
    events: ["show.changed", "show.cue_changed"],
    tasks: ["show.blocker"],
    legacySources: ["transient realtime payload as authority"],
    migrationState: "canonical-read",
    retirementCriteria: ["Realtime invalidates cached state and the client re-reads canonical show truth."],
  },
  {
    id: "incident",
    canonicalWriteModel: "incident lifecycle",
    canonicalReadProjection: "incident command projection",
    organizerProjection: "Incident Command",
    commands: ["incident.transition", "incident.assign"],
    events: ["incident.changed"],
    tasks: ["incident.response"],
    legacySources: ["free-form operational alerts"],
    migrationState: "canonical-write",
    retirementCriteria: ["SEV workflows derive from one canonical incident lifecycle."],
  },
  {
    id: "notification",
    canonicalWriteModel: "domain-event notification candidate + delivery lifecycle",
    canonicalReadProjection: "recipient Notification Centre projection",
    participantProjection: "Inbox/push/badge",
    organizerProjection: "Notification diagnostics",
    commands: ["notification.mark_read", "notification.retry_safe"],
    events: ["notification.queued", "notification.delivered", "notification.failed"],
    tasks: ["notification.delivery_failed"],
    legacySources: ["push payload as business truth", "unread count as task count"],
    migrationState: "canonical-read",
    retirementCriteria: ["Push, Inbox and badges are projections and never replace the underlying domain/task truth."],
  },
] as const;

export function solarisV6Domain(id: string) {
  return SOLARIS_V6_DOMAINS.find((domain) => domain.id === id) ?? null;
}
