/** Pure, explainable friend-voting model v2. Statistical signals are for review, never guilt findings. */
export const FRIEND_VOTING_MODEL_VERSION = "friend-voting-model-v2";
export type AdvancedFriendVotingObservation = { editionId: string; channel: "jury" | "televote"; voterId: string; targetCode: string; score: number; maxScore: number; supported?: boolean; maximum?: boolean; rank?: number | null; participantCount?: number | null };
export type AdvancedFriendVotingNetworkSignal = { score?: number; members?: number; density?: number; internalShare?: number; reason?: string };
export type AdvancedFriendVotingConfig = { bayesianPriorAlpha: number; bayesianPriorBeta: number; relationshipAnomalyWeight: number; historicalDeviationWeight: number; reciprocityWeight: number; intensityWeight: number; juryWeight: number; televoteWeight: number; crossChannelWeight: number; networkWeight: number; countryStrengthWeight: number; minimumEvidenceForStrongRisk: number; oneEditionCap: number; twoEditionCap: number };
export const DEFAULT_ADVANCED_FRIEND_VOTING_CONFIG: AdvancedFriendVotingConfig = { bayesianPriorAlpha: 1, bayesianPriorBeta: 1, relationshipAnomalyWeight: 20, historicalDeviationWeight: 20, reciprocityWeight: 15, intensityWeight: 10, juryWeight: 10, televoteWeight: 10, crossChannelWeight: 5, networkWeight: 10, countryStrengthWeight: 10, minimumEvidenceForStrongRisk: 3, oneEditionCap: 29, twoEditionCap: 49 };
export type AdvancedFriendVotingResult = { overallRisk: number; confidence: number; juryRisk: number; televoteRisk: number; crossChannelRisk: number; relationshipAnomaly: number; reciprocityRisk: number; intensityRisk: number; historicalDeviationRisk: number; networkRisk: number; countryStrengthRisk: number; reasons: string[]; warnings: string[]; sampleSize: { editions: number; opportunities: number; juryOpportunities: number; televoteOpportunities: number; historicalBaseline: number }; evidence: { observedSupport: number; eligibleSupport: number; smoothedSupportRate: number; averageScore: number; expectedAverageScore: number; maximumScores: number; reciprocalEditions: number; reciprocalSupportEditions: number; crossChannelEditions: number; historicalMaxScoreRate: number }; modelVersion: string };
const clamp = (n: number, min = 0, max = 100) => Math.max(min, Math.min(max, Number.isFinite(n) ? n : min));
const clamp01 = (n: number) => clamp(n, 0, 1);
const mean = (v: number[]) => v.length ? v.reduce((a, b) => a + b, 0) / v.length : 0;
const sd = (v: number[]) => { if (v.length < 2) return 0; const m = mean(v); return Math.sqrt(mean(v.map((x) => (x - m) ** 2))); };
const pct = (n: number) => `${Math.round(clamp01(n) * 1000) / 10}%`;
const round = (n: number, d = 2) => { const p = 10 ** d; return Math.round(n * p) / p; };
function beta(successes: number, trials: number, alpha: number, betaPrior: number) { return trials <= 0 ? clamp01(alpha / Math.max(1, alpha + betaPrior)) : clamp01((Math.max(0, successes) + Math.max(0, alpha)) / (trials + Math.max(0, alpha) + Math.max(0, betaPrior))); }
function zRisk(z: number) { return clamp(100 * (1 - Math.exp(-Math.min(5, Math.max(0, z)) / 1.75))); }
function weighted(parts: Array<[number, number]>) { const usable = parts.filter(([, w]) => w > 0 && Number.isFinite(w)); const total = usable.reduce((s, [, w]) => s + w, 0); return total ? usable.reduce((s, [v, w]) => s + clamp(v) * w, 0) / total : 0; }
function dedupe(rows: AdvancedFriendVotingObservation[], relationshipScope: boolean) {
  const map = new Map<string, AdvancedFriendVotingObservation>();
  for (const row of rows) {
    const key = relationshipScope ? `${row.editionId}:${row.channel}` : `${row.editionId}:${row.channel}:${row.voterId}:${row.targetCode}`;
    const old = map.get(key);
    if (!old) { map.set(key, { ...row, score: Number(row.score) || 0, maxScore: Number(row.maxScore) || 0 }); continue; }
    map.set(key, { ...old, score: (old.score + (Number(row.score) || 0)) / 2, maxScore: Math.max(old.maxScore, Number(row.maxScore) || 0), supported: Boolean(old.supported || row.supported || row.score > 0), maximum: Boolean(old.maximum || row.maximum) });
  }
  return [...map.values()];
}

export function calculateAdvancedFriendVotingRisk(pairObservations: AdvancedFriendVotingObservation[], allObservations: AdvancedFriendVotingObservation[], reciprocalSupportRate = 0, reciprocalEditions = 0, network: AdvancedFriendVotingNetworkSignal | null = null, config: AdvancedFriendVotingConfig = DEFAULT_ADVANCED_FRIEND_VOTING_CONFIG): AdvancedFriendVotingResult {
  const pair = dedupe(pairObservations, true); const all = dedupe(allObservations, false); const editions = new Set(pair.map((r) => r.editionId)); const jury = pair.filter((r) => r.channel === "jury"); const televote = pair.filter((r) => r.channel === "televote");
  const supported = pair.filter((r) => r.supported ?? r.score > 0).length; const maximum = pair.filter((r) => r.maximum ?? (r.score > 0 && r.score === r.maxScore)).length; const opportunities = pair.length;
  const voterId = pair[0]?.voterId; const targetCode = pair[0]?.targetCode;
  const targetHistory = all.filter((r) => r.voterId === voterId && r.targetCode === targetCode && !editions.has(r.editionId));
  const voterHistory = all.filter((r) => r.voterId === voterId && r.targetCode !== targetCode);
  const baseline = targetHistory.length ? targetHistory : voterHistory;
  const baselineScores = baseline.map((r) => Number(r.score) || 0); const observedAverage = mean(pair.map((r) => Number(r.score) || 0)); const expectedAverage = baselineScores.length ? mean(baselineScores) : 0; const historicalDeviationRisk = baselineScores.length >= 2 && expectedAverage !== 0 ? zRisk(Math.abs(observedAverage - expectedAverage) / Math.max(sd(baselineScores), 1)) : 0;
  const voterIntensity = all.filter((r) => r.voterId === voterId && r.maxScore > 0).map((r) => clamp01(r.score / r.maxScore)); const pairIntensity = pair.filter((r) => r.maxScore > 0).map((r) => clamp01(r.score / r.maxScore)); const expectedIntensity = mean(voterIntensity); const observedIntensity = mean(pairIntensity);
  const maximumRate = opportunities ? maximum / opportunities : 0; const historicalMaximumRate = baseline.length ? baseline.filter((r) => r.maxScore > 0 && r.score === r.maxScore && r.score > 0).length / baseline.length : 0; const intensityRisk = clamp(100 * (0.55 * clamp01(Math.abs(observedIntensity - expectedIntensity) / Math.max(0.08, expectedIntensity || 0.08)) + 0.45 * Math.abs(maximumRate - historicalMaximumRate)));
  const smoothedSupportRate = beta(supported, opportunities, config.bayesianPriorAlpha, config.bayesianPriorBeta); const relationshipAnomaly = clamp(100 * (0.5 * smoothedSupportRate * Math.min(1, opportunities / 8) + 0.3 * clamp01(Math.abs(observedAverage - expectedAverage) / 12) + 0.2 * maximumRate));
  const jurySupported = jury.filter((r) => r.supported ?? r.score > 0).length; const televoteSupported = televote.filter((r) => r.supported ?? r.score > 0).length;
  const juryRisk = jury.length ? weighted([[100 * beta(jurySupported, jury.length, config.bayesianPriorAlpha, config.bayesianPriorBeta) * Math.min(1, jury.length / 8), 0.65], [historicalDeviationRisk, 0.35]]) : 0;
  const televoteRisk = televote.length ? weighted([[100 * beta(televoteSupported, televote.length, config.bayesianPriorAlpha, config.bayesianPriorBeta) * Math.min(1, televote.length / 8), 0.65], [historicalDeviationRisk, 0.35]]) : 0;
  const crossChannelEditions = [...editions].filter((id) => { const c = new Set(pair.filter((r) => r.editionId === id && (r.supported ?? r.score > 0)).map((r) => r.channel)); return c.has("jury") && c.has("televote"); }).length; const crossChannelRisk = clamp(100 * (editions.size ? crossChannelEditions / editions.size : 0) * Math.min(1, editions.size / 6));
  const reciprocityRisk = clamp(100 * beta(reciprocalSupportRate * reciprocalEditions, reciprocalEditions, config.bayesianPriorAlpha, config.bayesianPriorBeta) * Math.min(1, reciprocalEditions / 6)); const networkRisk = clamp(network?.score ?? 0);
  const residuals: number[] = []; for (const row of pair) { const field = all.filter((r) => r.editionId === row.editionId && r.channel === row.channel && r.targetCode === row.targetCode && r.voterId !== row.voterId); if (!field.length || row.maxScore <= 0) continue; const fieldAvg = mean(field.filter((r) => r.maxScore > 0).map((r) => r.score / r.maxScore)); residuals.push(Math.abs(clamp01(row.score / row.maxScore) - fieldAvg)); }
  const countryStrengthRisk = clamp(100 * mean(residuals) * Math.min(1, residuals.length / 4)); const baseRisk = weighted([[relationshipAnomaly, config.relationshipAnomalyWeight], [historicalDeviationRisk, config.historicalDeviationWeight], [reciprocityRisk, config.reciprocityWeight], [intensityRisk, config.intensityWeight], [juryRisk, config.juryWeight], [televoteRisk, config.televoteWeight], [crossChannelRisk, config.crossChannelWeight], [networkRisk, config.networkWeight]]); let overallRisk = clamp(baseRisk + (countryStrengthRisk - 50) * Math.min(1, config.countryStrengthWeight / 100));
  if (editions.size < 2) overallRisk = Math.min(overallRisk, config.oneEditionCap); else if (editions.size < 3) overallRisk = Math.min(overallRisk, config.twoEditionCap);
  const evidenceFactor = 1 - Math.exp(-opportunities / 5); const editionFactor = 1 - Math.exp(-editions.size / 3); const baselineFactor = Math.min(1, baseline.length / 8); const consistency = pairIntensity.length > 1 ? 1 - clamp01(sd(pairIntensity) / 0.5) : 0.5; const channelFactor = pair.length ? 0.75 + 0.25 * Math.min(1, new Set(pair.map((r) => r.channel)).size / 2) : 0; const confidence = clamp(100 * (0.35 * evidenceFactor + 0.35 * editionFactor + 0.2 * baselineFactor + 0.1 * consistency) * channelFactor);
  const reasons: string[] = []; const warnings: string[] = [];
  if (supported && smoothedSupportRate >= 0.7 && editions.size >= 2) reasons.push(`Repeated support in ${pct(supported / Math.max(1, opportunities))} of eligible observations (${supported}/${opportunities})`);
  if (baseline.length >= 2 && historicalDeviationRisk >= 60) reasons.push(`Observed average score (${round(observedAverage, 1)}) differs unusually from the historical baseline (${round(expectedAverage, 1)})`);
  if (maximumRate >= 0.4 && editions.size >= 2) reasons.push(`Maximum-score concentration is ${pct(maximumRate)}, versus ${pct(historicalMaximumRate)} in the available baseline`);
  if (reciprocalEditions && reciprocalSupportRate >= 0.6) reasons.push(`Reciprocal support occurred in ${pct(reciprocalSupportRate)} of comparable editions`);
  if (crossChannelEditions) reasons.push(`The relationship appears in both jury and televote in ${crossChannelEditions} edition${crossChannelEditions === 1 ? "" : "s"}`);
  if (countryStrengthRisk < 25 && pair.length >= 2) reasons.push("The target is broadly strong in the same voting fields, reducing the relationship-specific anomaly signal"); if (networkRisk >= 65 && network?.reason) reasons.push(network.reason);
  if (editions.size < config.minimumEvidenceForStrongRisk) warnings.push(`Only ${editions.size} independent edition${editions.size === 1 ? "" : "s"} are available; risk is capped and should not be treated as a strong conclusion`); if (baseline.length < 2) warnings.push("Insufficient target-specific historical baseline; historical-deviation risk is conservative"); if (!jury.length) warnings.push("No jury observations are available for this relationship"); if (!televote.length) warnings.push("No televote observations are available for this relationship");
  return { overallRisk: Math.round(overallRisk), confidence: Math.round(confidence), juryRisk: Math.round(juryRisk), televoteRisk: Math.round(televoteRisk), crossChannelRisk: Math.round(crossChannelRisk), relationshipAnomaly: Math.round(relationshipAnomaly), reciprocityRisk: Math.round(reciprocityRisk), intensityRisk: Math.round(intensityRisk), historicalDeviationRisk: Math.round(historicalDeviationRisk), networkRisk: Math.round(networkRisk), countryStrengthRisk: Math.round(countryStrengthRisk), reasons, warnings, sampleSize: { editions: editions.size, opportunities, juryOpportunities: jury.length, televoteOpportunities: televote.length, historicalBaseline: baseline.length }, evidence: { observedSupport: supported, eligibleSupport: opportunities, smoothedSupportRate, averageScore: observedAverage, expectedAverageScore: expectedAverage, maximumScores: maximum, reciprocalEditions, reciprocalSupportEditions: Math.round(clamp01(reciprocalSupportRate) * reciprocalEditions), crossChannelEditions, historicalMaxScoreRate: historicalMaximumRate }, modelVersion: FRIEND_VOTING_MODEL_VERSION };
}
