#!/usr/bin/env bash
set -euo pipefail

log() { printf '\n[browser-e2e-seed] %s\n' "$*"; }
fail() { printf '\n[browser-e2e-seed] FAIL: %s\n' "$*" >&2; exit 1; }

# Read credentials generated by the local Supabase CLI. Nothing here may fall
# back to a hosted project.
eval "$(supabase status -o env)"
: "${API_URL:?missing local Supabase API_URL}"
: "${DB_URL:?missing local Supabase DB_URL}"
: "${ANON_KEY:?missing local Supabase ANON_KEY}"
: "${SERVICE_ROLE_KEY:?missing local Supabase SERVICE_ROLE_KEY}"

case "$API_URL" in
  http://127.0.0.1:*|http://localhost:*) ;;
  *) fail "refusing to seed browser E2E accounts against non-local API_URL=$API_URL" ;;
esac

case "$DB_URL" in
  postgresql://postgres:postgres@127.0.0.1:*/*|postgresql://postgres:postgres@localhost:*/*) ;;
  *) fail "refusing to seed browser E2E data against non-local DB_URL" ;;
esac

PASSWORD='SolarisBrowserLocal2026!'
ORGANIZER_EMAIL='organizer-browser-e2e@solaris.invalid'
ORGANIZER_B_EMAIL='organizer-b-browser-e2e@solaris.invalid'
COUNTRY_EMAIL='country-browser-e2e@solaris.invalid'
SUSPENDED_EMAIL='suspended-browser-e2e@solaris.invalid'

HTTP_BODY=''
HTTP_STATUS=''
LAST_USER_ID=''

json_value() {
  local path="$1"
  python3 -c '
import json, sys
path = sys.argv[1].split(".") if sys.argv[1] else []
value = json.load(sys.stdin)
for key in path:
    value = value[int(key)] if isinstance(value, list) else value[key]
print("" if value is None else value)
' "$path"
}

request() {
  local method="$1"
  local url="$2"
  local bearer="$3"
  local api_key="$4"
  local data="${5-}"
  local output
  output="$(mktemp)"
  local args=(
    -sS -o "$output" -w '%{http_code}' -X "$method" "$url"
    -H "apikey: $api_key"
    -H "Authorization: Bearer $bearer"
    -H "Content-Type: application/json"
  )
  if [[ -n "$data" ]]; then
    args+=(--data "$data")
  fi
  HTTP_STATUS="$(curl "${args[@]}")"
  HTTP_BODY="$(cat "$output")"
  rm -f "$output"
}

create_user() {
  local email="$1"
  local display_name="$2"
  local body
  body="$(python3 -c '
import json, sys
print(json.dumps({
  "email": sys.argv[1],
  "password": sys.argv[2],
  "email_confirm": True,
  "user_metadata": {"display_name": sys.argv[3]},
}))
' "$email" "$PASSWORD" "$display_name")"

  request POST "$API_URL/auth/v1/admin/users" "$SERVICE_ROLE_KEY" "$SERVICE_ROLE_KEY" "$body"
  if (( HTTP_STATUS < 200 || HTTP_STATUS >= 300 )); then
    fail "create local auth user $email returned HTTP $HTTP_STATUS: $HTTP_BODY"
  fi
  LAST_USER_ID="$(printf '%s' "$HTTP_BODY" | json_value id)"
  [[ -n "$LAST_USER_ID" ]] || fail "local auth response for $email had no user id"
}

db_exec() {
  psql "$DB_URL" -v ON_ERROR_STOP=1 -q -c "$1" >/dev/null
}

db_scalar() {
  psql "$DB_URL" -v ON_ERROR_STOP=1 -Atq -c "$1"
}

log "Seeding minimal local contest fixture"
db_exec "
insert into public.countries (id, name, short_code, region)
values
  ('00000000-0000-4000-8000-00000000e201'::uuid, 'Browserland', 'BRW', 'E2E'),
  ('00000000-0000-4000-8000-00000000e202'::uuid, 'Testovia', 'TST', 'E2E')
on conflict (id) do update
set name = excluded.name,
    short_code = excluded.short_code,
    region = excluded.region;

insert into public.editions (
  id, name, slug, edition_number, year, status, published
)
values (
  '00000000-0000-4000-8000-00000000e220'::uuid,
  'Browser Audit Edition',
  'ssc22',
  22,
  2026,
  'active',
  true
)
on conflict (id) do update
set name = excluded.name,
    slug = excluded.slug,
    edition_number = excluded.edition_number,
    status = excluded.status,
    published = excluded.published;
"

log "Creating local-only browser identities"
create_user "$ORGANIZER_EMAIL" "Browser Organizer"
ORGANIZER_ID="$LAST_USER_ID"
create_user "$ORGANIZER_B_EMAIL" "Browser Organizer B"
ORGANIZER_B_ID="$LAST_USER_ID"
create_user "$COUNTRY_EMAIL" "Browser HOD"
COUNTRY_ID="$LAST_USER_ID"
create_user "$SUSPENDED_EMAIL" "Suspended Browser HOD"
SUSPENDED_ID="$LAST_USER_ID"

log "Granting local authoritative access"
db_exec "
insert into public.studio2_role_assignments (
  user_id, role_key, edition_id, expires_at, assigned_by
)
values
  ('$ORGANIZER_ID'::uuid, 'organizer', null, null, null),
  ('$ORGANIZER_B_ID'::uuid, 'organizer', null, null, null)
on conflict on constraint studio2_role_assignments_scope_unique do nothing;

insert into public.country_accounts (
  user_id, country_id, status, suspension_reason, instagram_username, display_name
)
values
  (
    '$COUNTRY_ID'::uuid,
    '00000000-0000-4000-8000-00000000e201'::uuid,
    'active',
    null,
    'browser_hod',
    'Browser HOD'
  ),
  (
    '$SUSPENDED_ID'::uuid,
    '00000000-0000-4000-8000-00000000e202'::uuid,
    'suspended',
    'Local browser audit fixture',
    'suspended_browser_hod',
    'Suspended Browser HOD'
  )
on conflict (user_id) do update
set country_id = excluded.country_id,
    status = excluded.status,
    suspension_reason = excluded.suspension_reason,
    instagram_username = excluded.instagram_username,
    display_name = excluded.display_name,
    updated_at = now();
"

[[ "$(db_scalar "select count(*) from public.studio2_role_assignments where user_id in ('$ORGANIZER_ID'::uuid,'$ORGANIZER_B_ID'::uuid) and role_key='organizer';")" == "2" ]]   || fail "Both Organizer authoritative roles were not created"
[[ "$(db_scalar "select count(*) from public.studio2_role_assignments where user_id='$ORGANIZER_B_ID'::uuid and role_key='organizer';")" == "1" ]]   || fail "Second Organizer authoritative role was not created"
[[ "$(db_scalar "select status from public.country_accounts where user_id='$COUNTRY_ID'::uuid;")" == "active" ]]   || fail "Country browser account was not active"
[[ "$(db_scalar "select status from public.country_accounts where user_id='$SUSPENDED_ID'::uuid;")" == "suspended" ]]   || fail "Suspended browser account was not suspended"

# Export only throwaway local browser credentials. The local service-role key is
# intentionally NOT written to GITHUB_ENV.
if [[ -n "${GITHUB_ENV:-}" ]]; then
  {
    echo "E2E_ORGANIZER_EMAIL=$ORGANIZER_EMAIL"
    echo "E2E_ORGANIZER_PASSWORD=$PASSWORD"
    echo "E2E_ORGANIZER_B_EMAIL=$ORGANIZER_B_EMAIL"
    echo "E2E_ORGANIZER_B_PASSWORD=$PASSWORD"
    echo "E2E_COUNTRY_EMAIL=$COUNTRY_EMAIL"
    echo "E2E_COUNTRY_PASSWORD=$PASSWORD"
    echo "E2E_SUSPENDED_EMAIL=$SUSPENDED_EMAIL"
    echo "E2E_SUSPENDED_PASSWORD=$PASSWORD"
  } >> "$GITHUB_ENV"
else
  log "GITHUB_ENV is unavailable; local accounts were seeded but credentials were not exported."
fi

log "Local browser E2E fixture ready"
