import type { BetaSection } from "./types";

const discoveryResult = [
  "Found immediately",
  "Found after looking around",
  "Found, but it was difficult",
  "Could not find it",
];

const workedResult = ["Worked", "Something was wrong", "Could not use it", "Didn't test"];
const comparison = ["Much worse", "Worse", "About the same", "Better", "Much better", "I don't remember enough to compare"];

export const betaSectionsV2: BetaSection[] = [
  {
    id: "tester-profile",
    title: "1. Tester profile",
    description: "A little context so we know whether a response comes from a newcomer, a regular user or a Beta 1 tester.",
    questions: [
      { id: "testerName", label: "Name / SSC username", type: "text", required: true, placeholder: "Your name or SSC username" },
      { id: "country", label: "Country", type: "text", required: true, placeholder: "Your SSC country" },
      { id: "device", label: "Device used for this test", type: "single", required: true, options: ["Phone", "Tablet", "Laptop", "Desktop"] },
      { id: "browser", label: "Browser", type: "single", required: true, options: ["Chrome", "Safari", "Firefox", "Edge", "Other / Not sure"] },
      { id: "currentUse", label: "Have you used the current Solaris Studio before this beta test?", type: "single", required: true, options: ["Never", "Once or twice", "Several times", "I use it regularly"] },
      { id: "beta1Participant", label: "Did you participate in Beta 1?", type: "single", required: true, options: ["Yes", "No", "Not sure"] },
      { id: "beta1Memory", label: "How well do you remember Beta 1?", type: "single", options: ["Barely", "A little", "Quite well", "Very well"], showWhen: { id: "beta1Participant", equals: "Yes" } },
    ],
  },
  {
    id: "capabilities",
    title: "2. What Solaris Studio is supposed to do",
    description: "Read this before the discovery tasks. It tells you what exists, but deliberately does not tell you where it is.",
    task: {
      body: "Solaris Studio should let you browse editions, countries, shows, entries and results; explore Records, Relationships, Analysis and Pulse; create and use a country account; manage your country through My Solaris; find and edit confirmation responses; edit country information; customise Country and Wiki pages; manage design, colours, content and media; view and edit SSC entries; and find help when needed. During the discovery tasks, DO NOT use the Guide unless the task specifically tells you to. Do not ask another tester where something is.",
    },
    questions: [
      { id: "discoveryRules", label: "I understand that the next tasks should be completed without the Guide or help from another tester.", type: "single", required: true, options: ["I understand"] },
    ],
  },
  {
    id: "unaided-discovery",
    title: "3. Unaided discovery test",
    description: "Complete these in order. We are testing whether Solaris Studio itself makes the route obvious.",
    task: {
      body: "Start from the normal public Solaris Studio. Do not use the Guide. Complete the tasks below naturally, without being told which menu or page contains the feature.",
      href: "/",
      linkLabel: "Open Solaris Studio",
    },
    questions: [
      { id: "accountCreateSuccess", label: "Task 1 · Create your country account and enter My Solaris. How did discovery go?", type: "single", required: true, options: discoveryResult },
      { id: "accountCreateEase", label: "How easy was account creation?", type: "rating", required: true, lowLabel: "Very difficult", highLabel: "Effortless" },
      { id: "accountCreateConfidence", label: "How confident were you that you understood what you were doing?", type: "rating", required: true, lowLabel: "Not confident", highLabel: "Completely confident" },
      { id: "accountUsernameClear", label: "Was it clear which username to use?", type: "single", options: ["Yes", "Mostly", "No"] },
      { id: "accountEmailClear", label: "Was it clear what the optional recovery email was for?", type: "single", options: ["Yes", "Mostly", "No", "I didn't notice it"] },
      { id: "mySolarisMeaningClear", label: "Once signed in, did you understand what My Solaris was for?", type: "single", options: ["Yes immediately", "Mostly", "Not really", "No"] },
      { id: "confirmationFindSuccess", label: "Task 2 · Without a recovery code, find your country's confirmation response. How did discovery go?", type: "single", required: true, options: discoveryResult },
      { id: "confirmationAutoRecognised", label: "Did Solaris automatically recognise your country and show your existing response?", type: "single", required: true, options: ["Yes", "No", "I had no existing response", "Not sure"] },
      { id: "confirmationRecoveryAsked", label: "Were you asked for a recovery code even though you were signed in to the country account?", type: "single", required: true, options: ["No", "Yes", "Not sure"] },
      { id: "confirmationEditWorked", label: "Change something in the confirmation and save it. What happened?", type: "single", required: true, options: ["Saved correctly", "Saved, but it was not obvious", "Something went wrong", "I could not edit it", "I had no editable response"] },
      { id: "confirmationRefreshStayed", label: "After refreshing, was your change still there?", type: "single", options: ["Yes", "No", "I didn't check", "I couldn't save"] },
      { id: "mySolarisCountryFind", label: "Task 3A · Find where you would change basic country information.", type: "single", required: true, options: discoveryResult },
      { id: "mySolarisAppearanceFind", label: "Task 3B · Find where you would change the public page appearance.", type: "single", required: true, options: discoveryResult },
      { id: "mySolarisEntryFind", label: "Task 3C · Find where you would edit an SSC entry.", type: "single", required: true, options: discoveryResult },
      { id: "mySolarisMediaFind", label: "Task 3D · Find where you would add or change page media.", type: "single", required: true, options: discoveryResult },
      { id: "mySolarisOverwhelming", label: "How overwhelming did My Solaris feel?", type: "rating", required: true, lowLabel: "Not overwhelming at all", highLabel: "Extremely overwhelming" },
      { id: "countryEditorFind", label: "Task 4 · Find where you can customise your country's public page.", type: "single", required: true, options: discoveryResult },
      { id: "countryEditActions", label: "Try changing a colour, personality/design, content and an image/media item where possible.", type: "matrix", required: true, rows: ["Change a colour", "Change personality/design", "Change content", "Add/change media", "Save changes", "See the change publicly"], options: ["Worked", "Something was wrong", "Couldn't find it", "Didn't test"] },
      { id: "countryWikiDifference", label: "Was it obvious which changes affected the Country page and which affected the Wiki page?", type: "single", options: ["Yes", "Mostly", "No", "I wasn't sure there was a difference"] },
      { id: "publicCountryFind", label: "Task 5A · Find your public Country page without a direct link.", type: "single", required: true, options: discoveryResult },
      { id: "publicWikiFind", label: "Task 5B · Find your public Wiki page without a direct link.", type: "single", required: true, options: discoveryResult },
      { id: "publicDiscovery", label: "Task 6 · Find SSC21, Oland's SSC21 entry, Oland's placement, the full voting result and something showing Oland's longer-term history.", type: "matrix", required: true, rows: ["Find SSC21", "Find Oland's entry", "Find Oland's placement", "Find the full voting result", "Find longer-term Oland history"], options: discoveryResult },
      { id: "searchTargetResult", label: "Task 7 · Find Oland's SSC21 entry using whatever method feels natural. How quickly did you find it?", type: "single", required: true, options: ["Immediately", "Eventually", "Only after trying several things", "Could not find it"] },
      { id: "searchMethod", label: "How did you find it?", type: "single", options: ["Search", "Edition page", "Country page", "Wiki", "Results / another route", "I couldn't find it"] },
      { id: "guideFind", label: "Task 8 · Now imagine you do not know how to change your Country page design. Find the Guide and the answer.", type: "single", required: true, options: discoveryResult },
      { id: "guideQuality", label: "How well did the Guide work once you found it?", type: "matrix", required: true, rows: ["Easy to find the right answer", "Language was easy to understand", "Answer actually solved the problem", "Organisation made sense"], options: ["Very poor", "Poor", "Okay", "Good", "Very good"] },
      { id: "guidePurpose", label: "In your own words, what is the Guide for?", type: "textarea", placeholder: "I think the Guide is for..." },
      { id: "discoveryConfusion", label: "What confused you most during the discovery tasks?", type: "textarea", helper: "Optional. A few words are enough." },
    ],
  },
  {
    id: "navigation",
    title: "4. Navigation test",
    questions: [
      { id: "navStatements", label: "How much do you agree with these statements?", type: "matrix", required: true, rows: ["I always knew where I was", "I usually knew what to click next", "Important features were where I expected", "Moving between the public site and My Solaris made sense", "Buttons and menu names clearly explained what they did"], options: ["Strongly disagree", "Disagree", "Neither", "Agree", "Strongly agree"] },
      { id: "navDifferences", label: "How clear were these differences?", type: "matrix", required: true, rows: ["Country page vs Wiki", "Public site vs My Solaris", "The My Solaris sections", "Pulse vs Analysis", "Results vs Full Scorecharts"], options: ["Completely unclear", "Mostly unclear", "Somewhat clear", "Clear", "Completely clear"] },
      { id: "feltLost", label: "How often did you feel lost?", type: "single", required: true, options: ["Never", "Once", "A few times", "Often"] },
      { id: "lostDoingWhat", label: "What were you trying to do when you felt lost?", type: "textarea", showWhen: { id: "feltLost", oneOf: ["Once", "A few times", "Often"] } },
    ],
  },
  {
    id: "my-solaris",
    title: "5. My Solaris test",
    description: "The new My Solaris is deliberately split into smaller workspaces instead of placing almost everything on one endless page.",
    task: { body: "Open My Solaris and move through Overview, Country, Page & media and Entries. Try to understand each section before answering.", href: "/country-hub", linkLabel: "Open My Solaris" },
    questions: [
      { id: "mySolarisUnderstand", label: "How easy was each section to understand?", type: "matrix", required: true, rows: ["Overview", "Country", "Page & media", "Entries"], options: ["Very hard", "Hard", "Okay", "Easy", "Very easy"] },
      { id: "mySolarisFindThings", label: "How easy was it to find things inside each section?", type: "matrix", required: true, rows: ["Overview", "Country", "Page & media", "Entries"], options: ["Very hard", "Hard", "Okay", "Easy", "Very easy"] },
      { id: "mySolarisAmount", label: "How did the amount of information feel?", type: "matrix", required: true, rows: ["Overview", "Country", "Page & media", "Entries"], options: ["Too little", "A little too little", "About right", "A little too much", "Too much"] },
      { id: "mySolarisWrongSection", label: "Was anything placed in a section where you would not expect it?", type: "multi", options: ["Country information", "Confirmation response", "Appearance", "Wiki/page content", "Media/images", "SSC entries", "Account/profile information", "Nothing felt misplaced"] },
      { id: "mySolarisSplitBetter", label: "Compared with having almost everything on one page, separating My Solaris into sections feels…", type: "single", options: comparison },
      { id: "mySolarisComment", label: "What would you move, remove or make easier in My Solaris?", type: "textarea", helper: "Optional." },
    ],
  },
  {
    id: "country-account",
    title: "6. Country account functionality",
    description: "Mark what you actually tested. A warning or failure will be more useful than pretending everything worked.",
    questions: [
      { id: "countryAccountChecklist", label: "Country account checklist", type: "matrix", required: true, rows: ["Create account", "Sign in", "Sign out", "Optional recovery email", "Password recovery", "My Solaris Overview", "Country information", "Confirmation response", "Automatic confirmation access", "Country page editor", "Wiki/page content", "Page & media", "Appearance", "Entries", "Saving", "Public preview", "Navigation", "Guide"], options: workedResult },
      { id: "countryAccountProblem", label: "If anything was wrong or unusable, what happened?", type: "textarea", helper: "Only describe the important failures. You can report reproducible bugs later." },
    ],
  },
  {
    id: "public-site",
    title: "7. Public Solaris Studio",
    task: { body: "Explore the homepage, Editions, Countries, Shows, Wiki, Analysis, Pulse, Relationships, Records and a few Tools. Do not try to test every tiny thing.", href: "/", linkLabel: "Open public Solaris Studio" },
    questions: [
      { id: "homepagePurpose", label: "After looking at the homepage, what do you think Solaris Studio is mainly for?", type: "textarea", required: true, placeholder: "I think Solaris Studio is mainly for..." },
      { id: "homepageCapabilities", label: "Which things did the homepage make you think Solaris Studio can do?", type: "multi", options: ["Browse editions/results", "Explore countries/Wiki", "Use a country account", "Edit country information", "Explore Analysis/Records/Relationships", "Follow recent activity in Pulse", "Make predictions", "Use result/archive tools", "Vote / participate", "I wasn't sure"] },
      { id: "publicExplore", label: "How clear were the main Explore pages?", type: "matrix", required: true, rows: ["Editions", "Countries", "Shows", "Wiki"], options: ["Very unclear", "Unclear", "Okay", "Clear", "Very clear"] },
      { id: "publicInsights", label: "How clear were the main Insights pages?", type: "matrix", required: true, rows: ["Analysis", "Pulse", "Relationships", "Records"], options: ["Very unclear", "Unclear", "Okay", "Clear", "Very clear"] },
      { id: "toolsTriedV2", label: "Which tools did you try? Choose at least two if possible.", type: "multi", options: ["Result Lab", "Taste DNA", "Broadcast Intelligence", "Jury Replay", "Archive Games", "Compare countries", "Full Scorecharts", "Prediction Arena"] },
      { id: "publicComment", label: "What part of the public site still feels least finished?", type: "textarea" },
    ],
  },
  {
    id: "pulse",
    title: "8. Pulse re-test",
    task: { body: "Explore Solaris Pulse for a while without reading the Guide first. Open whatever catches your attention naturally.", href: "/pulse", linkLabel: "Open Solaris Pulse" },
    questions: [
      { id: "pulsePurposeV2", label: "What do you think Solaris Pulse is for?", type: "textarea", required: true },
      { id: "pulseOpenedMultiple", label: "Did you open more than one story/update?", type: "single", required: true, options: ["Yes", "No"] },
      { id: "pulseCatchUp", label: "Did you use Catch me up?", type: "single", options: ["Yes", "No", "I didn't notice it"] },
      { id: "pulseNumbers", label: "Did you explore a Numbers worth knowing story?", type: "single", options: ["Yes", "No", "I didn't notice one"] },
      { id: "pulseLeftThroughLink", label: "Did Pulse make you open another country, edition, result or Analysis page?", type: "single", options: ["Yes", "No"] },
      { id: "pulseSemantic", label: "Pulse feels…", type: "matrix", required: true, rows: ["Interesting", "Easy to scan", "Alive / current", "Worth checking regularly"], options: ["Not at all", "A little", "Somewhat", "Quite", "Very"] },
      { id: "pulseWantExplore", label: "Did Pulse make you want to explore anything else on Solaris Studio?", type: "single", options: ["Definitely", "A little", "Not really", "No"] },
    ],
  },
  {
    id: "analysis",
    title: "9. Analysis re-test",
    task: { body: "Open Analysis without the Guide. Start with Discover, then open at least one deeper view.", href: "/analysis", linkLabel: "Open Analysis" },
    questions: [
      { id: "analysisPurposeV2", label: "In your own words, what is Analysis for?", type: "textarea", required: true },
      { id: "discoverMakesSense", label: "How well did Discover make sense without explanation?", type: "rating", required: true, lowLabel: "Not at all", highLabel: "Completely" },
      { id: "discoverUseful", label: "Were the Discover stories useful or interesting?", type: "single", options: ["Yes, a lot", "Some were", "Not really", "No"] },
      { id: "discoverWhyInteresting", label: "Could you understand why the stories were interesting or unusual?", type: "single", options: ["Yes", "Mostly", "No"] },
      { id: "analysisFurther", label: "Did you know how to explore further from Discover?", type: "single", options: ["Yes immediately", "After looking around", "Not really", "No"] },
      { id: "analysisVisualOverwhelm", label: "Did anything in Analysis feel visually overwhelming?", type: "single", options: ["No", "A little", "Yes"] },
      { id: "analysisVisualDetail", label: "What felt overwhelming?", type: "textarea", showWhen: { id: "analysisVisualOverwhelm", oneOf: ["A little", "Yes"] } },
      { id: "analysisBeta1Compare", label: "Compared with Beta 1, Analysis is…", type: "single", options: comparison, showWhen: { id: "beta1Participant", equals: "Yes" } },
    ],
  },
  {
    id: "results",
    title: "10. Results re-test",
    description: "Judge the interface, not whether every old point total or historical result has been added correctly.",
    task: { body: "Find an overall result, switch between Jury / Televote / Overall, compare entries, find a Full Scorechart, inspect a close result and find one highlighted fact.", href: "/shows", linkLabel: "Open Shows" },
    questions: [
      { id: "resultsTasksV2", label: "How did each result task go?", type: "matrix", required: true, rows: ["Find overall result", "Switch Jury / Televote / Overall", "Compare entries", "Find Full Scorechart", "Understand a close result", "Find a highlighted fact"], options: ["Easy", "Worked after looking", "Difficult", "Could not do it"] },
      { id: "resultsDensity", label: "How did the amount of information on result pages feel?", type: "single", options: ["Much too little", "A little too little", "About right", "A little too much", "Much too much"] },
      { id: "resultsVisuals", label: "Did charts/highlighted facts help you understand the result?", type: "single", options: ["Yes, a lot", "A little", "Not really", "I didn't notice them"] },
      { id: "resultsCommentV2", label: "What is still awkward about navigating or understanding results?", type: "textarea" },
    ],
  },
  {
    id: "country-design",
    title: "11. Country page design",
    task: { body: "Open the public Country page you created BEFORE returning to the editor. Judge the finished public page itself first.", href: "/countries", linkLabel: "Open Countries" },
    questions: [
      { id: "countryDesignRatings", label: "Rate the finished country page", type: "matrix", required: true, rows: ["Visual quality", "Modern feeling", "Readability", "Layout", "Country identity", "Colour use", "Flag integration", "Amount of empty space", "Mobile appearance", "Consistency"], options: ["Very poor", "Poor", "Okay", "Good", "Excellent"] },
      { id: "countryDesignSemantic", label: "Which side is the page closer to?", type: "matrix", required: true, rows: ["Generic ↔ Distinctive", "Messy ↔ Organised", "Outdated ↔ Modern", "Cramped ↔ Spacious", "Empty ↔ Complete", "Template-like ↔ Personal", "Flag pasted on ↔ Flag part of the design"], options: ["Far left", "Mostly left", "Middle", "Mostly right", "Far right"] },
      { id: "countryDesignBest", label: "What looks best on the page?", type: "textarea" },
      { id: "countryDesignWorst", label: "What still looks wrong or unfinished?", type: "textarea" },
    ],
  },
  {
    id: "personalities",
    title: "12. Personality / design comparison",
    task: { body: "Try at least THREE different page personalities: one you would naturally choose, one you would normally ignore, and one that looks very different from the first two.", href: "/country-hub", linkLabel: "Open My Solaris" },
    questions: [
      { id: "personalitiesTried", label: "Which personalities did you test?", type: "multi", required: true, options: ["Classic", "Editorial", "Minimal", "Flag focus", "Poster", "Split", "Spotlight", "Broadcast", "Panorama", "Monument", "Glass card", "Newspaper", "Ribbon", "Duotone", "Passport", "Horizon"] },
      { id: "personalityOverall", label: "Across the personalities you tried, how well did these things work?", type: "matrix", required: true, rows: ["Looks good", "Flag fits naturally", "Text is readable", "Colours work correctly", "Layout feels balanced", "No awkward empty areas", "Designs feel different from each other", "I would actually use at least one"], options: ["Very poor", "Poor", "Okay", "Good", "Excellent"] },
      { id: "personalityFavourite", label: "Favourite personality", type: "single", required: true, optionsFrom: "personalitiesTried" },
      { id: "personalityLeast", label: "Least favourite personality", type: "single", required: true, optionsFrom: "personalitiesTried" },
      { id: "personalityWhy", label: "Why did you choose those as favourite and least favourite?", type: "textarea", required: true },
      { id: "personalitySimilar", label: "Which two personalities felt too similar, if any?", type: "text", placeholder: "Example: ___ and ___" },
    ],
  },
  {
    id: "missing-designs",
    title: "13. What designs are missing?",
    questions: [
      { id: "designStylesWanted", label: "What kinds of country page designs would you like to see more of?", type: "multi", options: ["Minimal / clean", "Editorial / magazine", "Futuristic", "Glass / translucent", "Bold / graphic", "Elegant / luxurious", "Dark", "Colourful", "Flag-focused", "Photo-focused", "Data/statistics-focused", "Eurovision/broadcast inspired", "Traditional / cultural", "Clean data dashboard", "Experimental", "Other"] },
      { id: "designOnePriority", label: "If Solaris added ONE new design category, which should it be?", type: "single", optionsFrom: "designStylesWanted" },
      { id: "designWish", label: "Describe one country page style you wish existed.", type: "textarea", helper: "Optional." },
    ],
  },
  {
    id: "responsive",
    title: "14. Mobile / responsive test",
    task: { body: "Use the navigation, My Solaris, Country editor, public Country page, Wiki, results, Analysis and Pulse on your device. On desktop, resize the browser once. On mobile, rotate once if practical.", href: "/", linkLabel: "Continue testing" },
    questions: [
      { id: "responsiveAreas", label: "Which areas did you check on this device?", type: "multi", options: ["Navigation drawer", "My Solaris sections", "Country editor", "Public Country page", "Wiki", "Results", "Analysis", "Pulse"] },
      { id: "responsiveProblemsV2", label: "Which problems did you see?", type: "multi", required: true, options: ["Text cut off", "Elements overlapping", "Horizontal scrolling", "Text too small", "Hard-to-tap controls", "Pages feel too long", "Something disappearing", "Huge useless empty area", "None of these"] },
      { id: "responsiveWhereV2", label: "Where did the problem happen?", type: "textarea", showWhen: { id: "responsiveProblemsV2", notEquals: "None of these" }, helper: "If you chose None of these, leave this blank." },
      { id: "responsiveComfort", label: "How comfortable was Solaris Studio to use on this device?", type: "rating", required: true, lowLabel: "Very uncomfortable", highLabel: "Excellent" },
    ],
  },
  {
    id: "beta1-comparison",
    title: "15. Beta 1 → Beta 2 comparison",
    description: "Only Beta 1 testers need to compare. The old findings below are the real first-beta results, not invented averages.",
    questions: [
      { id: "beta1SearchCompare", label: "Beta 1: only 5 of 11 testers found their search target immediately. Finding things now feels…", type: "single", options: comparison, showWhen: { id: "beta1Participant", equals: "Yes" } },
      { id: "beta1EntriesCompare", label: "Beta 1: 3 of 11 testers could not find a country's entries and another needed searching. Finding entries now feels…", type: "single", options: comparison, showWhen: { id: "beta1Participant", equals: "Yes" } },
      { id: "beta1AnalysisCompare", label: "Beta 1: 4 testers said Analysis needed more explanation. Analysis now feels…", type: "single", options: comparison, showWhen: { id: "beta1Participant", equals: "Yes" } },
      { id: "beta1PulseCompare", label: "Beta 1: 7 of 11 testers explored Pulse only a little or not really. Pulse now feels…", type: "single", options: comparison, showWhen: { id: "beta1Participant", equals: "Yes" } },
      { id: "beta1MobileCompare", label: "Beta 1: 6 of 11 testers hit at least one visual/responsive problem. Mobile/layout quality now feels…", type: "single", options: comparison, showWhen: { id: "beta1Participant", equals: "Yes" } },
      { id: "beta1BroadCompare", label: "Broader Beta 1 → Beta 2 comparison", type: "matrix", rows: ["Overall design", "Navigation", "Finding features", "Ease of use", "Instructions", "My Solaris", "Country pages", "Analysis", "Pulse", "Mobile", "Overall quality"], options: comparison, showWhen: { id: "beta1Participant", equals: "Yes" } },
      { id: "beta1BiggestImprovement", label: "What is the biggest improvement since Beta 1?", type: "textarea", showWhen: { id: "beta1Participant", equals: "Yes" } },
      { id: "beta1StillNotFixed", label: "What still feels like it has not been properly fixed since Beta 1?", type: "textarea", showWhen: { id: "beta1Participant", equals: "Yes" } },
      { id: "beta1DidBetter", label: "Did Beta 1 do anything better than Beta 2?", type: "textarea", showWhen: { id: "beta1Participant", equals: "Yes" } },
      { id: "notBeta1Note", label: "You did not take Beta 1, so this section is intentionally short. Continue to the next section.", type: "single", options: ["Continue"], showWhen: { id: "beta1Participant", oneOf: ["No", "Not sure"] } },
    ],
  },
  {
    id: "incomplete-data",
    title: "16. Incomplete historical data",
    task: { body: "Some historical Solaris data is still incomplete. Do NOT mark a feature as broken simply because an old edition, entry or result has not been added yet. Judge whether the information that IS available is easy to find, understandable and displayed correctly." },
    questions: [
      { id: "dataWarningUnderstood", label: "I understand that missing historical data should not lower my UI/functionality rating by itself.", type: "single", required: true, options: ["I understand"] },
      { id: "availableDataClarity", label: "For the data that is available, how clearly is it presented?", type: "rating", required: true, lowLabel: "Very unclear", highLabel: "Extremely clear" },
    ],
  },
  {
    id: "bugs",
    title: "17. Bug reporting",
    description: "Report reproducible problems here. Device, browser and screen size are saved automatically with the submission.",
    questions: [
      { id: "bugsFound", label: "Did you find any bug that you have not already explained well enough above?", type: "single", required: true, options: ["No", "Yes"] },
    ],
  },
  {
    id: "psychological-ux",
    title: "18. Psychological UX",
    description: "These measure how the site feels to operate, not whether you liked its colours.",
    questions: [
      { id: "uxConfidence", label: "How confident did you feel that you understood what you were doing?", type: "rating", required: true, lowLabel: "Not confident", highLabel: "Completely confident" },
      { id: "uxMentalEffort", label: "How mentally tiring was Solaris Studio to use?", type: "rating", required: true, lowLabel: "Effortless", highLabel: "Exhausting" },
      { id: "uxTrust", label: "When Solaris said something was saved or changed, how much did you trust that it really had?", type: "rating", required: true, lowLabel: "Did not trust it", highLabel: "Completely trusted it" },
      { id: "uxHesitation", label: "How often did you stop because you were not sure which button to press?", type: "single", required: true, options: ["Never", "Rarely", "Sometimes", "Often", "Very often"] },
      { id: "uxSpeed", label: "How responsive did Solaris Studio feel?", type: "rating", required: true, lowLabel: "Very slow", highLabel: "Very fast" },
      { id: "uxEnjoyment", label: "How enjoyable was Solaris Studio to explore?", type: "rating", required: true, lowLabel: "Not enjoyable", highLabel: "Extremely enjoyable" },
      { id: "uxControl", label: "I felt I could undo, change or fix things if I made a mistake.", type: "rating", required: true, lowLabel: "Strongly disagree", highLabel: "Strongly agree" },
    ],
  },
  {
    id: "priorities",
    title: "19. Forced priorities",
    description: "Do not try to fix everything at once. Pick what matters most before release.",
    questions: [
      { id: "priorityThree", label: "Choose the THREE areas Solaris should improve most before release.", type: "multi", required: true, options: ["Account creation/sign-in", "My Solaris", "Confirmations", "Country/Wiki editor", "Country page designs", "Navigation", "Homepage", "Editions/results", "Search/discovery", "Guide/instructions", "Pulse", "Analysis", "Relationships", "Records", "Tools", "Mobile/responsive quality", "Speed", "Saving/feedback messages"] },
      { id: "priorityOne", label: "Which ONE of those should be fixed first?", type: "single", required: true, optionsFrom: "priorityThree" },
      { id: "priorityWhy", label: "Why does that one matter most?", type: "textarea" },
    ],
  },
  {
    id: "final-ratings",
    title: "20. Final ratings",
    description: "Only now do we ask for the overall judgement, after you have actually tested the individual parts.",
    questions: [
      { id: "overallV2", label: "Overall Solaris Studio V2", type: "rating", required: true, lowLabel: "Very poor", highLabel: "Excellent" },
      { id: "easeV2", label: "Overall ease of use", type: "rating", required: true, lowLabel: "Very difficult", highLabel: "Effortless" },
      { id: "releaseReadinessV2", label: "How ready does V2 feel for public release?", type: "rating", required: true, lowLabel: "0% ready", highLabel: "100% ready" },
      { id: "wouldUseV2", label: "Would you personally use Solaris Studio during SSC?", type: "single", required: true, options: ["Definitely", "Probably", "Maybe", "Probably not", "Definitely not"] },
      { id: "recommendV2", label: "Would you recommend Solaris Studio to another SSC member?", type: "rating", required: true, lowLabel: "Definitely not", highLabel: "Definitely" },
      { id: "betterIfV2", label: "Finish the sentence: Solaris Studio would be much better if…", type: "textarea", required: true, placeholder: "Solaris Studio would be much better if..." },
    ],
  },
];
