import {
  BarChart3,
  BellRing,
  BookOpen,
  Calculator,
  ClipboardCheck,
  Database,
  Eye,
  FileClock,
  FileLock2,
  Flag,
  FlaskConical,
  Gavel,
  GitBranch,
  History,
  Images,
  KeyRound,
  LayoutDashboard,
  Layers3,
  ListVideo,
  Mail,
  MapPinned,
  MessageCircleQuestion,
  PlayCircle,
  RadioTower,
  Settings2,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Sparkles,
  Trophy,
  Vote,
  type LucideIcon,
} from "lucide-react";

type AdminNavigationItemBase = {
  id: string;
  label: string;
  description: string;
  icon: LucideIcon;
  keywords: string;
  active: (pathname: string) => boolean;
};

export type AdminNavigationItem =
  | (AdminNavigationItemBase & {
      availability: "ready";
      to: string;
    })
  | (AdminNavigationItemBase & {
      availability: "requires-edition";
      to: null;
      unavailableReason: "Select an edition first";
    });

export type AdminNavigationGroup = {
  label: string;
  description: string;
  items: AdminNavigationItem[];
  quiet?: boolean;
};

// These identifiers are deliberately independent from routes. Edition routes
// become available after data loads, while React identity must remain stable.
const ADMIN_NAVIGATION_IDS = {
  Overview: "current-edition-overview",
  Tasks: "current-edition-tasks",
  Delegations: "current-edition-delegations",
  Contest: "current-edition-contest",
  Host: "current-edition-host",
  Voting: "current-edition-voting",
  "Voting declarations": "current-edition-voting-declarations",
  "Results operations": "current-edition-results",
  Storytelling: "current-edition-storytelling",
  Publish: "current-edition-publish",
  Broadcast: "current-edition-broadcast",
  "Control Room": "operations-control-room",
  Workflows: "operations-workflows",
  Incidents: "operations-incidents",
  Eligibility: "operations-eligibility",
  "Media assets": "operations-media-assets",
  Communications: "operations-communications",
  "Reveal Director": "live-review-reveal-director",
  "Broadcast rundown": "live-review-broadcast-rundown",
  "Simulation Lab": "live-review-simulation-lab",
  "Time Machine": "live-review-time-machine",
  "Voting Lab": "live-review-voting-lab",
  "Confirmation overview": "delegation-confirmation-overview",
  "Confirmation requirements": "delegation-confirmation-requirements",
  "Confirmation responses": "delegation-confirmation-responses",
  "Next in Line": "delegation-next-in-line",
  "Responses by country": "delegation-responses-by-country",
  "Submission rounds": "delegation-submission-rounds",
  "Delegation calendar": "delegation-calendar",
  "Delegation access": "delegation-access",
  "Submission history": "delegation-submission-history",
  "Confirmation edition links": "delegation-edition-links",
  "Confirmation sync": "delegation-sync",
  "Confirmation settings": "delegation-settings",
  "Voting rounds & entries": "voting-rounds-entries",
  "Jury voting": "voting-jury",
  "Voting rules": "voting-rules",
  "Jury integrity": "voting-jury-integrity",
  "Televote totals": "voting-televote-totals",
  "Voting integrity review": "voting-integrity-review",
  "Public vote results": "voting-public-results",
  "Voting intelligence": "voting-intelligence",
  "Voting analytics": "voting-analytics",
  "Combined result tools": "voting-combined-results",
  "Result integrity": "voting-result-integrity",
  "Voting audit log": "voting-audit-log",
  "Voting edition links": "voting-edition-links",
  "Result backtest": "voting-result-backtest",
  "Anti-abuse review": "voting-anti-abuse",
  Investigations: "trust-investigations",
  "Rule rulings": "trust-rule-rulings",
  Appeals: "trust-appeals",
  Evidence: "trust-evidence",
  Disclosure: "trust-disclosure",
  "Identity access": "trust-identity-access",
  "Rules manager": "trust-rules-manager",
  Interpretations: "trust-interpretations",
  "Public rules": "trust-public-rules",
  "Access & permissions": "workspace-access-permissions",
  Administration: "workspace-administration",
  "Feature rollout": "workspace-feature-rollout",
  "All editions": "workspace-all-editions",
  "Organizer guide": "workspace-organizer-guide",
  "Country accounts": "workspace-country-accounts",
  "Flag QA": "workspace-flag-qa",
  "HOD history": "workspace-hod-history",
  "Community moderation": "workspace-community-moderation",
  Predictions: "workspace-predictions",
  "Fantasy SSC": "workspace-fantasy",
  "Command Assistant": "workspace-command-assistant",
  "Anniversary settings": "workspace-anniversary-settings",
  "Anniversary dates": "workspace-anniversary-dates",
  "Public UX": "workspace-public-ux",
  "Beta 3 feedback": "workspace-beta-3-feedback",
  "Beta 2 feedback": "workspace-beta-2-feedback",
  "Beta 1 archive": "workspace-beta-1-archive",
  "Organizer acceptance test": "workspace-acceptance-test",
  "Organizer beta coverage": "workspace-beta-coverage",
  "System health": "workspace-system-health",
  "Delivery & jobs": "workspace-delivery-jobs",
  "System settings": "workspace-system-settings",
} as const;

type AdminNavigationLabel = keyof typeof ADMIN_NAVIGATION_IDS;

export function buildAdminNavigation(slug?: string): AdminNavigationGroup[] {
  const editionHref = slug ? `/admin/${slug}` : null;
  const publishHref = slug ? `/admin/publication/${slug}` : null;
  const broadcastHref = slug ? `/admin/design/${slug}` : null;

  return [
    {
      label: "Current edition",
      description: "The main contest, delegation, voting and publication workspaces.",
      items: [
        item(
          "Overview",
          "Edition status, priorities and next actions.",
          "/admin/operations",
          LayoutDashboard,
          "home status priorities",
          (path) => path.startsWith("/admin/operations"),
        ),
        item(
          "Tasks",
          "Every unresolved organizer action, blocker and due item.",
          "/admin/tasks",
          BellRing,
          "alerts blockers deadlines tasks",
          (path) =>
            path.startsWith("/admin/tasks") ||
            path.startsWith("/admin/action-center") ||
            path.startsWith("/admin/action-centre"),
        ),
        item(
          "Delegations",
          "Country readiness, confirmations and delegation access.",
          "/admin/countries",
          ClipboardCheck,
          "countries confirmations responses delegation",
          (path) => path.startsWith("/admin/countries") || path.startsWith("/confirmations/admin"),
        ),
        item(
          "Contest",
          "Shows, entries, line-ups and participation for the selected edition.",
          editionHref,
          Layers3,
          "shows entries lineup participation contest",
          (path) =>
            (slug ? path === `/admin/${slug}` : false) ||
            path.startsWith("/admin/shows/") ||
            path.startsWith("/admin/entries/") ||
            path.startsWith("/admin/lineup-sync/") ||
            path.startsWith("/admin/participant-status/"),
        ),
        item(
          "Host",
          "Host bids, selection, venues and delivery readiness.",
          "/admin/hosts",
          MapPinned,
          "hosting bids city venue operations",
          (path) => path.startsWith("/admin/hosts"),
        ),
        item(
          "Voting",
          "Voting rules, juries, televote and voting integrity.",
          "/televoting/admin",
          Vote,
          "jury televote public voting rules points",
          (path) =>
            (path.startsWith("/televoting/admin") &&
              !path.startsWith("/televoting/admin/integrity-declarations")) ||
            path.startsWith("/admin/jury/") ||
            path.startsWith("/admin/voting-system/") ||
            path.startsWith("/admin/televote/") ||
            path.startsWith("/admin/friend-voting") ||
            path.startsWith("/admin/jury-integrity"),
        ),
        item(
          "Voting declarations",
          "Inspect the signed voting-integrity declarations.",
          "/televoting/admin/integrity-declarations",
          FileLock2,
          "voting integrity declarations signed",
          (path) => path.startsWith("/televoting/admin/integrity-declarations"),
        ),
        item(
          "Results operations",
          "Review, lock and release the official result lifecycle.",
          "/admin/results",
          Calculator,
          "results calculate review lock publish",
          (path) => path.startsWith("/admin/results") && !path.startsWith("/admin/results-reveal"),
        ),
        item(
          "Storytelling",
          "Edition stories, archive moments and anniversary publishing.",
          "/admin/storytelling",
          BookOpen,
          "stories anniversary narrative archive",
          (path) => path.startsWith("/admin/storytelling"),
        ),
        item(
          "Publish",
          "Control exactly what becomes public and when.",
          publishHref,
          Eye,
          "publication visibility release public",
          (path) => path.startsWith("/admin/publication/"),
        ),
        item(
          "Broadcast",
          "Edition design, scoreboard and live presentation.",
          broadcastHref,
          RadioTower,
          "design theme scoreboard broadcast",
          (path) => path.startsWith("/admin/design/") || path.startsWith("/admin/edition-theme/"),
        ),
      ],
    },
    {
      label: "Operations",
      description: "Live coordination, readiness and communications.",
      items: [
        item(
          "Control Room",
          "Live edition state, incidents, voting and communications.",
          "/admin/control-room",
          ShieldAlert,
          "live command control status",
          (path) => path.startsWith("/admin/control-room"),
        ),
        item(
          "Workflows",
          "Operational workflows, dependencies and task state.",
          "/admin/workflows",
          GitBranch,
          "workflow tasks dependencies execution",
          (path) => path.startsWith("/admin/workflows"),
        ),
        item(
          "Incidents",
          "Open, command and resolve operational incidents.",
          "/admin/incidents",
          Siren,
          "incident sev crisis timeline",
          (path) => path.startsWith("/admin/incidents"),
        ),
        item(
          "Eligibility",
          "Country eligibility checks, blockers and overrides.",
          "/admin/eligibility",
          ShieldCheck,
          "eligibility countries overrides checks",
          (path) => path.startsWith("/admin/eligibility"),
        ),
        item(
          "Media assets",
          "Validate, review and approve contest media.",
          "/admin/media-assets",
          Images,
          "media artwork assets review",
          (path) => path.startsWith("/admin/media-assets"),
        ),
        item(
          "Communications",
          "Draft, schedule and publish official notices.",
          "/admin/communications",
          Mail,
          "notice messages communications publish",
          (path) => path.startsWith("/admin/communications"),
        ),
      ],
    },
    {
      label: "Live & review",
      description: "Specialist rehearsal, reveal and audit tools.",
      items: [
        item(
          "Reveal Director",
          "Plan and rehearse the results reveal sequence.",
          "/admin/results-reveal",
          Sparkles,
          "results reveal strategy sequence",
          (path) => path.startsWith("/admin/results-reveal"),
        ),
        item(
          "Broadcast rundown",
          "Build the live show rundown and cue sequence.",
          "/admin/broadcast-rundown",
          ListVideo,
          "broadcast rundown cues show",
          (path) => path.startsWith("/admin/broadcast-rundown"),
        ),
        item(
          "Simulation Lab",
          "Rehearse an edition without changing canonical state.",
          "/admin/edition-simulator",
          PlayCircle,
          "edition simulator rehearsal archive replay",
          (path) => path.startsWith("/admin/edition-simulator"),
        ),
        item(
          "Time Machine",
          "Inspect recorded historical edition state without mutating production.",
          "/admin/time-machine",
          History,
          "history snapshot time machine replay audit",
          (path) => path.startsWith("/admin/time-machine"),
        ),
        item(
          "Voting Lab",
          "Test voting scenarios and integrity signals safely.",
          "/admin/voting-lab",
          FlaskConical,
          "voting lab simulation test",
          (path) => path.startsWith("/admin/voting-lab"),
        ),
      ],
    },
    {
      label: "Delegation tools",
      description: "Detailed confirmation, response, round and access tools.",
      quiet: true,
      items: [
        item(
          "Confirmation overview",
          "Open the full delegation-confirmation workspace.",
          "/confirmations/admin",
          ClipboardCheck,
          "confirmations delegations overview",
          (path) => path === "/confirmations/admin" || path === "/confirmations/admin/",
        ),
        item(
          "Confirmation requirements",
          "Manage one current edition-level confirmation obligation per delegation.",
          "/confirmations/admin/requirements",
          ClipboardCheck,
          "confirmation requirements generations reconfirm waive delegation",
          (path) => path.startsWith("/confirmations/admin/requirements"),
        ),
        item(
          "Confirmation responses",
          "Review submitted delegation confirmations and entry details.",
          "/confirmations/admin/responses",
          ClipboardCheck,
          "confirmation responses review submissions",
          (path) => path.startsWith("/confirmations/admin/responses"),
        ),
        item(
          "Next in Line",
          "Review side-competition participation and unused-song submissions.",
          "/admin/next-in-line",
          Sparkles,
          "next in line side competition submissions",
          (path) => path.startsWith("/admin/next-in-line"),
        ),
        item(
          "Responses by country",
          "Inspect confirmation state and historical context country by country.",
          "/confirmations/admin/countries",
          Flag,
          "confirmation countries delegation status",
          (path) => path.startsWith("/confirmations/admin/countries"),
        ),
        item(
          "Submission rounds",
          "Create and manage confirmation submission windows.",
          "/confirmations/admin/rounds",
          FileClock,
          "confirmation rounds opens closes",
          (path) => path.startsWith("/confirmations/admin/rounds"),
        ),
        item(
          "Delegation calendar",
          "See confirmation workflow dates in calendar form.",
          "/confirmations/admin/calendar",
          FileClock,
          "confirmation calendar dates schedule",
          (path) => path.startsWith("/confirmations/admin/calendar"),
        ),
        item(
          "Delegation access",
          "Manage recovery codes and confirmation access.",
          "/confirmations/admin/recovery-codes",
          KeyRound,
          "confirmation access recovery codes",
          (path) => path.startsWith("/confirmations/admin/recovery-codes"),
        ),
        item(
          "Submission history",
          "Inspect confirmation versions and restoration history.",
          "/admin/submission-versions",
          History,
          "submissions versions restore history",
          (path) => path.startsWith("/admin/submission-versions"),
        ),
        item(
          "Confirmation edition links",
          "Inspect the confirmation service projection of Solaris editions.",
          "/confirmations/admin/editions",
          Trophy,
          "confirmation editions links sync",
          (path) => path.startsWith("/confirmations/admin/editions"),
        ),
        item(
          "Confirmation sync",
          "Inspect and repair confirmation integration synchronization.",
          "/confirmations/admin/sync",
          Database,
          "confirmation sync integration health",
          (path) => path.startsWith("/confirmations/admin/sync"),
        ),
        item(
          "Confirmation settings",
          "Low-frequency confirmation service settings.",
          "/confirmations/admin/settings",
          Settings2,
          "confirmation settings service",
          (path) => path.startsWith("/confirmations/admin/settings"),
        ),
      ],
    },
    {
      label: "Voting specialist tools",
      description: "Detailed voting, integrity, audit and result-verification tools.",
      quiet: true,
      items: [
        item(
          "Voting rounds & entries",
          "Create, schedule and manage public voting rounds and their eligible entries.",
          "/televoting/admin/rounds",
          PlayCircle,
          "voting rounds entries open close schedule",
          (path) => path.startsWith("/televoting/admin/rounds"),
        ),
        item(
          "Jury voting",
          "Manage jury rosters, ballots and completion for the selected edition.",
          slug ? `/admin/jury/${slug}` : null,
          Vote,
          "jury voting ballots roster",
          (path) => path.startsWith("/admin/jury/"),
        ),
        item(
          "Voting rules",
          "Configure the voting system and point rules for the selected edition.",
          slug ? `/admin/voting-system/${slug}` : null,
          Calculator,
          "voting system rules points",
          (path) => path.startsWith("/admin/voting-system/"),
        ),
        item(
          "Jury integrity",
          "Review jury-independence and corroborating risk evidence.",
          "/admin/jury-integrity",
          ShieldCheck,
          "jury integrity independence risk evidence",
          (path) => path.startsWith("/admin/jury-integrity"),
        ),
        item(
          "Televote totals",
          "Review or enter aggregate televote points for a show.",
          slug ? `/admin/televote/${slug}` : null,
          Vote,
          "aggregate televote totals points",
          (path) => path.startsWith("/admin/televote/"),
        ),
        item(
          "Voting integrity review",
          "Review flagged public ballots and organizer moderation decisions.",
          "/televoting/admin/integrity",
          ShieldAlert,
          "voting integrity moderation blocked ballots",
          (path) => path.startsWith("/televoting/admin/integrity"),
        ),
        item(
          "Public vote results",
          "Calculate and review the public-vote result.",
          "/televoting/admin/results",
          Trophy,
          "televote results calculate review",
          (path) => path.startsWith("/televoting/admin/results"),
        ),
        item(
          "Voting intelligence",
          "Inspect advanced relationship and integrity intelligence.",
          "/televoting/admin/intelligence",
          BarChart3,
          "voting intelligence network anomalies",
          (path) => path.startsWith("/televoting/admin/intelligence"),
        ),
        item(
          "Voting analytics",
          "Turnout, point distribution and entry performance.",
          "/televoting/admin/analytics",
          BarChart3,
          "voting analytics turnout distribution",
          (path) => path.startsWith("/televoting/admin/analytics"),
        ),
        item(
          "Combined result tools",
          "Inspect how jury and public voting are combined.",
          "/televoting/admin/combined",
          Calculator,
          "combined result jury televote",
          (path) => path.startsWith("/televoting/admin/combined"),
        ),
        item(
          "Result integrity",
          "Test result sensitivity and support concentration.",
          "/televoting/admin/result-integrity",
          ShieldCheck,
          "result integrity influence concentration",
          (path) => path.startsWith("/televoting/admin/result-integrity"),
        ),
        item(
          "Voting audit log",
          "Trace voting, moderation and result operations.",
          "/televoting/admin/audit-log",
          History,
          "voting audit log history",
          (path) => path.startsWith("/televoting/admin/audit-log"),
        ),
        item(
          "Voting edition links",
          "Inspect the voting projection of Solaris editions.",
          "/televoting/admin/editions",
          Trophy,
          "voting editions links sync",
          (path) => path.startsWith("/televoting/admin/editions"),
        ),
        item(
          "Result backtest",
          "Run historical result and integrity backtests.",
          "/televoting/admin/backtest",
          FlaskConical,
          "voting result backtest simulation",
          (path) => path.startsWith("/televoting/admin/backtest"),
        ),
        item(
          "Anti-abuse review",
          "Inspect advanced anti-abuse evidence and controls.",
          "/televoting/admin/anti-abuse",
          ShieldAlert,
          "voting anti abuse moderation integrity",
          (path) => path.startsWith("/televoting/admin/anti-abuse"),
        ),
      ],
    },
    {
      label: "Trust & governance",
      description: "Rules, investigations, evidence and appeal safeguards.",
      items: [
        item(
          "Investigations",
          "Triage reports, review cases and record findings.",
          "/admin/integrity-investigations",
          ShieldCheck,
          "integrity cases reports findings",
          (path) =>
            path === "/admin/integrity" ||
            path.startsWith("/admin/integrity-investigations") ||
            path.startsWith("/admin/integrity-case/") ||
            path.startsWith("/admin/integrity-resolution/"),
        ),
        item(
          "Rule rulings",
          "Answer pre-clearance requests before a delegation acts.",
          "/admin/integrity-preclearance",
          MessageCircleQuestion,
          "preclearance ruling rules advice",
          (path) => path.startsWith("/admin/integrity-preclearance"),
        ),
        item(
          "Appeals",
          "Review sanctions through an independent appeal queue.",
          "/admin/integrity-appeals",
          Gavel,
          "appeals sanctions review",
          (path) => path.startsWith("/admin/integrity-appeals"),
        ),
        item(
          "Evidence",
          "Manage evidence access, retention and deletion lifecycle.",
          "/admin/integrity-evidence",
          Database,
          "evidence files retention cleanup",
          (path) => path.startsWith("/admin/integrity-evidence"),
        ),
        item(
          "Disclosure",
          "Review protected disclosure requests and decisions.",
          "/admin/integrity-disclosure",
          FileLock2,
          "disclosure confidential request",
          (path) => path.startsWith("/admin/integrity-disclosure"),
        ),
        item(
          "Identity access",
          "Control sealed-identity break-glass access.",
          "/admin/integrity-identity",
          KeyRound,
          "identity sealed access break glass",
          (path) => path.startsWith("/admin/integrity-identity"),
        ),
        item(
          "Rules manager",
          "Draft, validate and publish governed rulebook releases.",
          "/admin/rules-manager",
          FileClock,
          "rules rulebook version release governance",
          (path) => path.startsWith("/admin/rules-manager"),
        ),
        item(
          "Interpretations",
          "Publish official rule clarifications and precedent.",
          "/admin/rule-interpretations",
          MessageCircleQuestion,
          "interpretations clarification precedent",
          (path) => path.startsWith("/admin/rule-interpretations"),
        ),
        item(
          "Public rules",
          "Open the rulebook exactly as visitors see it.",
          "/rules",
          BookOpen,
          "public rules rulebook",
          (path) => path.startsWith("/rules"),
        ),
      ],
    },
    {
      label: "Workspace",
      description: "Accounts, editions, rollout controls and help.",
      quiet: true,
      items: [
        item(
          "Access & permissions",
          "Users, role presets, capabilities and authoritative access telemetry.",
          "/admin/access-permissions",
          KeyRound,
          "access users roles capabilities permissions audit",
          (path) => path.startsWith("/admin/access-permissions"),
        ),
        item(
          "Administration",
          "Accounts, HOD history, predictions and system tools.",
          "/admin/more",
          Settings2,
          "accounts history settings diagnostics",
          (path) => path.startsWith("/admin/more"),
        ),
        item(
          "Feature rollout",
          "See which Studio features are enabled or still planned.",
          "/admin/feature-rollout",
          Flag,
          "feature flags rollout enabled planned",
          (path) => path.startsWith("/admin/feature-rollout"),
        ),
        item(
          "All editions",
          "Create, archive and switch between SSC editions.",
          "/admin/editions",
          Trophy,
          "edition library create archive",
          (path) => path.startsWith("/admin/editions"),
        ),
        item(
          "Organizer guide",
          "Plain-language help for the main organizer workflows.",
          "/admin/guide",
          BookOpen,
          "guide help instructions",
          (path) => path.startsWith("/admin/guide"),
        ),
        item(
          "Country accounts",
          "Manage the sign-in account for each delegation.",
          "/admin/country-accounts",
          KeyRound,
          "country delegation accounts access",
          (path) => path.startsWith("/admin/country-accounts"),
        ),
        item(
          "Flag QA",
          "Review originals and adjust the shared 3:2 country flag crop.",
          "/admin/flag-audit",
          Flag,
          "country flags crop image audit",
          (path) => path.startsWith("/admin/flag-audit"),
        ),
        item(
          "HOD history",
          "Review Head of Delegation assignments by edition.",
          "/admin/hod-history",
          History,
          "head delegation history assignments",
          (path) => path.startsWith("/admin/hod-history"),
        ),
        item(
          "Community moderation",
          "Hide or restore public fan display identity without changing competitive data.",
          "/admin/community-moderation",
          ShieldCheck,
          "community moderation fan profile prediction league identity",
          (path) => path.startsWith("/admin/community-moderation"),
        ),
        item(
          "Predictions",
          "Create and manage visitor prediction rounds.",
          "/admin/predictions",
          Sparkles,
          "prediction rounds engagement",
          (path) => path.startsWith("/admin/predictions"),
        ),
        item(
          "Fantasy SSC",
          "Configure roster costs, budget, lock window and result scoring.",
          "/admin/fantasy",
          Trophy,
          "fantasy roster game costs leaderboard",
          (path) => path.startsWith("/admin/fantasy"),
        ),
        item(
          "Command Assistant",
          "Use the bounded read-only Organizer command registry.",
          "/admin/command-assistant",
          Sparkles,
          "assistant commands natural language organizer",
          (path) => path.startsWith("/admin/command-assistant"),
        ),
        item(
          "Anniversary settings",
          "Manage anniversary content and milestones.",
          "/admin/anniversary",
          Trophy,
          "anniversary settings milestones",
          (path) => path === "/admin/anniversary",
        ),
        item(
          "Anniversary dates",
          "Manage anniversary dates and archive moments.",
          "/admin/anniversary-dates",
          FileClock,
          "anniversary dates history",
          (path) => path.startsWith("/admin/anniversary-dates"),
        ),
        item(
          "Public UX",
          "Review public navigation, search and task-completion telemetry.",
          "/admin/public-ux",
          BarChart3,
          "public ux navigation search findability telemetry usability",
          (path) => path.startsWith("/admin/public-ux"),
        ),
        item(
          "Beta 3 feedback",
          "Review the navigation and findability study.",
          "/admin/beta3-feedback",
          BarChart3,
          "beta 3 navigation findability usability",
          (path) => path.startsWith("/admin/beta3-feedback"),
        ),
        item(
          "Beta 2 feedback",
          "Review current public-site usability feedback and comparisons.",
          "/admin/beta2-feedback",
          BarChart3,
          "beta feedback usability",
          (path) => path.startsWith("/admin/beta2-feedback"),
        ),
        item(
          "Beta 1 archive",
          "Read the closed Beta 1 responses and benchmarks.",
          "/admin/beta1-feedback",
          History,
          "beta archive feedback benchmark",
          (path) => path.startsWith("/admin/beta1-feedback"),
        ),
        item(
          "Organizer acceptance test",
          "Run and record the main organizer acceptance checks.",
          "/admin/beta-test",
          ClipboardCheck,
          "qa acceptance testing",
          (path) => path.startsWith("/admin/beta-test"),
        ),
        item(
          "Organizer beta coverage",
          "Review organizer test coverage and reported bugs.",
          "/admin/admin-beta-feedback",
          BarChart3,
          "qa beta coverage bugs",
          (path) => path.startsWith("/admin/admin-beta-feedback"),
        ),
        item(
          "System health",
          "Inspect data synchronization and integration health.",
          "/admin/sync-health",
          Settings2,
          "diagnostics sync health",
          (path) => path.startsWith("/admin/sync-health"),
        ),
        item(
          "Delivery & jobs",
          "Inspect push delivery state and Solaris scheduler runs.",
          "/admin/system-operations",
          BellRing,
          "system push notifications delivery jobs cron diagnostics",
          (path) => path.startsWith("/admin/system-operations"),
        ),
        item(
          "System settings",
          "Manage deadlines, audit history and maintenance controls.",
          "/admin/system",
          Settings2,
          "settings deadlines audit maintenance",
          (path) => path.startsWith("/admin/system"),
        ),
      ],
    },
  ];
}

function item(
  label: AdminNavigationLabel,
  description: string,
  to: string | null,
  icon: LucideIcon,
  keywords: string,
  active: (pathname: string) => boolean,
): AdminNavigationItem {
  const base = {
    id: ADMIN_NAVIGATION_IDS[label],
    label,
    description,
    icon,
    keywords,
    active,
  };

  return to === null
    ? {
        ...base,
        availability: "requires-edition",
        to: null,
        unavailableReason: "Select an edition first",
      }
    : { ...base, availability: "ready", to };
}
