/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RelationshipsIndexRouteImport } from './routes/relationships/index'
import { Route as RecordsIndexRouteImport } from './routes/records/index'
import { Route as EditionsIndexRouteImport } from './routes/editions/index'
import { Route as CountriesIndexRouteImport } from './routes/countries/index'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AnalysisIndexRouteImport } from './routes/analysis/index'
import { Route as ShowsShowIdRouteImport } from './routes/shows/$showId'
import { Route as RelationshipsPairRouteImport } from './routes/relationships/$pair'
import { Route as EditionsSlugRouteImport } from './routes/editions/$slug'
import { Route as CountriesCodeRouteImport } from './routes/countries/$code'
import { Route as BroadcastShowIdRouteImport } from './routes/broadcast/$showId'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminSlugRouteImport } from './routes/_authenticated/admin/$slug'
import { Route as AuthenticatedAdminDesignSlugRouteImport } from './routes/_authenticated/admin/design.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsIndexRoute = RelationshipsIndexRouteImport.update({
  id: '/relationships/',
  path: '/relationships/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIndexRoute = RecordsIndexRouteImport.update({
  id: '/records/',
  path: '/records/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsIndexRoute = EditionsIndexRouteImport.update({
  id: '/editions/',
  path: '/editions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/analysis/',
  path: '/analysis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsShowIdRoute = ShowsShowIdRouteImport.update({
  id: '/shows/$showId',
  path: '/shows/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const RelationshipsPairRoute = RelationshipsPairRouteImport.update({
  id: '/relationships/$pair',
  path: '/relationships/$pair',
  getParentRoute: () => rootRouteImport,
} as any)
const EditionsSlugRoute = EditionsSlugRouteImport.update({
  id: '/editions/$slug',
  path: '/editions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesCodeRoute = CountriesCodeRouteImport.update({
  id: '/countries/$code',
  path: '/countries/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastShowIdRoute = BroadcastShowIdRouteImport.update({
  id: '/broadcast/$showId',
  path: '/broadcast/$showId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSlugRoute = AuthenticatedAdminSlugRouteImport.update({
  id: '/admin/$slug',
  path: '/admin/$slug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDesignSlugRoute =
  AuthenticatedAdminDesignSlugRouteImport.update({
    id: '/admin/design/$slug',
    path: '/admin/design/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/broadcast/$showId': typeof BroadcastShowIdRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/editions/$slug': typeof EditionsSlugRoute
  '/relationships/$pair': typeof RelationshipsPairRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/editions/': typeof EditionsIndexRoute
  '/records/': typeof RecordsIndexRoute
  '/relationships/': typeof RelationshipsIndexRoute
  '/admin/$slug': typeof AuthenticatedAdminSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/design/$slug': typeof AuthenticatedAdminDesignSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/broadcast/$showId': typeof BroadcastShowIdRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/editions/$slug': typeof EditionsSlugRoute
  '/relationships/$pair': typeof RelationshipsPairRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/analysis': typeof AnalysisIndexRoute
  '/auth': typeof AuthIndexRoute
  '/compare': typeof CompareIndexRoute
  '/countries': typeof CountriesIndexRoute
  '/editions': typeof EditionsIndexRoute
  '/records': typeof RecordsIndexRoute
  '/relationships': typeof RelationshipsIndexRoute
  '/admin/$slug': typeof AuthenticatedAdminSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/design/$slug': typeof AuthenticatedAdminDesignSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/broadcast/$showId': typeof BroadcastShowIdRoute
  '/countries/$code': typeof CountriesCodeRoute
  '/editions/$slug': typeof EditionsSlugRoute
  '/relationships/$pair': typeof RelationshipsPairRoute
  '/shows/$showId': typeof ShowsShowIdRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/editions/': typeof EditionsIndexRoute
  '/records/': typeof RecordsIndexRoute
  '/relationships/': typeof RelationshipsIndexRoute
  '/_authenticated/admin/$slug': typeof AuthenticatedAdminSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/design/$slug': typeof AuthenticatedAdminDesignSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/broadcast/$showId'
    | '/countries/$code'
    | '/editions/$slug'
    | '/relationships/$pair'
    | '/shows/$showId'
    | '/analysis/'
    | '/auth/'
    | '/compare/'
    | '/countries/'
    | '/editions/'
    | '/records/'
    | '/relationships/'
    | '/admin/$slug'
    | '/admin/'
    | '/admin/design/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/broadcast/$showId'
    | '/countries/$code'
    | '/editions/$slug'
    | '/relationships/$pair'
    | '/shows/$showId'
    | '/analysis'
    | '/auth'
    | '/compare'
    | '/countries'
    | '/editions'
    | '/records'
    | '/relationships'
    | '/admin/$slug'
    | '/admin'
    | '/admin/design/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/sitemap.xml'
    | '/broadcast/$showId'
    | '/countries/$code'
    | '/editions/$slug'
    | '/relationships/$pair'
    | '/shows/$showId'
    | '/analysis/'
    | '/auth/'
    | '/compare/'
    | '/countries/'
    | '/editions/'
    | '/records/'
    | '/relationships/'
    | '/_authenticated/admin/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/design/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BroadcastShowIdRoute: typeof BroadcastShowIdRoute
  CountriesCodeRoute: typeof CountriesCodeRoute
  EditionsSlugRoute: typeof EditionsSlugRoute
  RelationshipsPairRoute: typeof RelationshipsPairRoute
  ShowsShowIdRoute: typeof ShowsShowIdRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  EditionsIndexRoute: typeof EditionsIndexRoute
  RecordsIndexRoute: typeof RecordsIndexRoute
  RelationshipsIndexRoute: typeof RelationshipsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships/': {
      id: '/relationships/'
      path: '/relationships'
      fullPath: '/relationships/'
      preLoaderRoute: typeof RelationshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/': {
      id: '/records/'
      path: '/records'
      fullPath: '/records/'
      preLoaderRoute: typeof RecordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions/': {
      id: '/editions/'
      path: '/editions'
      fullPath: '/editions/'
      preLoaderRoute: typeof EditionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/analysis'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$showId': {
      id: '/shows/$showId'
      path: '/shows/$showId'
      fullPath: '/shows/$showId'
      preLoaderRoute: typeof ShowsShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relationships/$pair': {
      id: '/relationships/$pair'
      path: '/relationships/$pair'
      fullPath: '/relationships/$pair'
      preLoaderRoute: typeof RelationshipsPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editions/$slug': {
      id: '/editions/$slug'
      path: '/editions/$slug'
      fullPath: '/editions/$slug'
      preLoaderRoute: typeof EditionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$code': {
      id: '/countries/$code'
      path: '/countries/$code'
      fullPath: '/countries/$code'
      preLoaderRoute: typeof CountriesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcast/$showId': {
      id: '/broadcast/$showId'
      path: '/broadcast/$showId'
      fullPath: '/broadcast/$showId'
      preLoaderRoute: typeof BroadcastShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/$slug': {
      id: '/_authenticated/admin/$slug'
      path: '/admin/$slug'
      fullPath: '/admin/$slug'
      preLoaderRoute: typeof AuthenticatedAdminSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/design/$slug': {
      id: '/_authenticated/admin/design/$slug'
      path: '/admin/design/$slug'
      fullPath: '/admin/design/$slug'
      preLoaderRoute: typeof AuthenticatedAdminDesignSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminSlugRoute: typeof AuthenticatedAdminSlugRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminDesignSlugRoute: typeof AuthenticatedAdminDesignSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminSlugRoute: AuthenticatedAdminSlugRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminDesignSlugRoute: AuthenticatedAdminDesignSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BroadcastShowIdRoute: BroadcastShowIdRoute,
  CountriesCodeRoute: CountriesCodeRoute,
  EditionsSlugRoute: EditionsSlugRoute,
  RelationshipsPairRoute: RelationshipsPairRoute,
  ShowsShowIdRoute: ShowsShowIdRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  EditionsIndexRoute: EditionsIndexRoute,
  RecordsIndexRoute: RecordsIndexRoute,
  RelationshipsIndexRoute: RelationshipsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
