begin;

-- Production has long used public.admin_audit_log for Solaris-side privileged
-- operations (for example Friend Voting settings and server-owned Organizer
-- actions), but the table itself predates the checked-in migration history. Keep
-- clean rebuilds aligned with production before Permission Engine v2 takes over
-- its read authorization.

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  table_name text not null,
  record_id text,
  edition_id uuid references public.editions(id) on delete set null,
  country_id uuid references public.countries(id) on delete set null,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_log_created_at_idx
  on public.admin_audit_log (created_at desc);
create index if not exists admin_audit_log_actor_idx
  on public.admin_audit_log (actor_id, created_at desc);
create index if not exists admin_audit_log_edition_idx
  on public.admin_audit_log (edition_id, created_at desc)
  where edition_id is not null;
create index if not exists admin_audit_log_country_idx
  on public.admin_audit_log (country_id, created_at desc)
  where country_id is not null;

alter table public.admin_audit_log enable row level security;

-- Server/service writers do not need a browser write policy. The following
-- cutover migration owns authenticated read access through permissions.audit.
revoke all on table public.admin_audit_log from anon, authenticated;
grant select on table public.admin_audit_log to authenticated;
grant all on table public.admin_audit_log to service_role;

commit;
