begin;

-- Final RLS + schema hygiene.
--
-- 1. Remove production-only, empty migration staging tables.
-- 2. Give the private notice-deletion audit log a durable primary key.
-- 3. Preserve the exact union of current anon/authenticated SELECT access while
--    consolidating it to one policy per role and splitting authenticated FOR ALL
--    write policies into INSERT / UPDATE / DELETE policies.
--
-- This removes policy-evaluation duplication without changing application
-- authorization semantics.

do $staging_cleanup$
declare
  v_table record;
  v_rows bigint;
begin
  if exists (select 1 from pg_namespace where nspname = 'migration_staging') then
    if exists (
      select 1
      from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace
      where n.nspname = 'migration_staging'
    ) then
      raise exception 'migration_staging contains functions and cannot be removed automatically';
    end if;

    for v_table in
      select c.oid, c.relname
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'migration_staging'
        and c.relkind = 'r'
      order by c.relname
    loop
      execute format('select count(*) from migration_staging.%I', v_table.relname)
        into v_rows;
      if v_rows <> 0 then
        raise exception 'migration_staging.% is not empty (% rows)', v_table.relname, v_rows;
      end if;

      if exists (
        select 1
        from pg_constraint con
        where con.contype = 'f'
          and con.confrelid = v_table.oid
          and con.conrelid <> v_table.oid
      ) then
        raise exception 'migration_staging.% is referenced by a foreign key', v_table.relname;
      end if;
    end loop;

    execute 'drop schema migration_staging cascade';
  end if;
end
$staging_cleanup$;

alter table private.studio2_notice_deletion_audit
  add column if not exists id bigint generated by default as identity;

do $notice_audit_pk$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'private.studio2_notice_deletion_audit'::regclass
      and contype = 'p'
  ) then
    alter table private.studio2_notice_deletion_audit
      add constraint studio2_notice_deletion_audit_pkey primary key (id);
  end if;
end
$notice_audit_pk$;

-- Add covering indexes only for currently material FK relationships on tables
-- with meaningful live production volume. Smaller/empty-table advisor findings
-- remain informational until workload growth justifies their write/storage cost.
create index if not exists contest_entities_country_id_idx
  on public.contest_entities(country_id);
create index if not exists country_hod_edition_claims_country_id_idx
  on public.country_hod_edition_claims(country_id);
create index if not exists country_hod_edition_claims_edition_id_idx
  on public.country_hod_edition_claims(edition_id);
create index if not exists jury_votes_receiving_country_id_idx
  on public.jury_votes(receiving_country_id);
create index if not exists jury_votes_voter_country_id_idx
  on public.jury_votes(voter_country_id);
create index if not exists jury_votes_voter_entity_id_idx
  on public.jury_votes(voter_entity_id);
create index if not exists participants_country_id_idx
  on public.participants(country_id);
create index if not exists results_country_id_idx
  on public.results(country_id);
create index if not exists televote_votes_country_id_idx
  on public.televote_votes(country_id);
create index if not exists voters_contest_entity_id_idx
  on public.voters(contest_entity_id);
create index if not exists voters_country_id_idx
  on public.voters(country_id);

do $policy_consolidation$
declare
  v_target record;
  v_policy record;
  v_anon_qual text;
  v_auth_qual text;
  v_roles_sql text;
  v_insert_name text;
  v_update_name text;
  v_delete_name text;
  v_check text;
begin
  for v_target in
    select *
    from (values
      ('public','content_events'),
      ('public','contest_entities'),
      ('public','countries'),
      ('public','country_accounts'),
      ('public','country_edition_identities'),
      ('public','country_hod_edition_claims'),
      ('public','country_media'),
      ('public','country_profile_sections'),
      ('public','country_profiles'),
      ('public','country_themes'),
      ('public','editions'),
      ('public','entries'),
      ('public','jury_ballot_submissions'),
      ('public','jury_votes'),
      ('public','jury_voting_windows'),
      ('public','participants'),
      ('public','prediction_rounds'),
      ('public','results'),
      ('public','shows'),
      ('public','submission_rounds'),
      ('public','televote_votes'),
      ('public','themes'),
      ('public','user_roles'),
      ('public','voters'),
      ('televoting','combined_televote_component_results'),
      ('televoting','combined_televote_results'),
      ('televoting','countries'),
      ('televoting','editions'),
      ('televoting','round_countries'),
      ('televoting','round_entries'),
      ('televoting','round_results'),
      ('televoting','rounds'),
      ('televoting','televote_aggregation_participants'),
      ('televoting','televote_aggregations')
    ) as targets(schema_name, table_name)
  loop
    if to_regclass(format('%I.%I', v_target.schema_name, v_target.table_name)) is null then
      raise exception 'Expected RLS table is missing: %.%', v_target.schema_name, v_target.table_name;
    end if;

    -- Capture the exact current SELECT union before changing any policy.
    select string_agg('(' || p.qual || ')', ' OR ' order by p.policyname)
    into v_anon_qual
    from pg_policies p
    where p.schemaname = v_target.schema_name
      and p.tablename = v_target.table_name
      and p.cmd in ('SELECT','ALL')
      and p.qual is not null
      and ('public' = any(p.roles) or 'anon' = any(p.roles));

    select string_agg('(' || p.qual || ')', ' OR ' order by p.policyname)
    into v_auth_qual
    from pg_policies p
    where p.schemaname = v_target.schema_name
      and p.tablename = v_target.table_name
      and p.cmd in ('SELECT','ALL')
      and p.qual is not null
      and ('public' = any(p.roles) or 'authenticated' = any(p.roles));

    -- Split every browser-applicable FOR ALL policy so it no longer contributes
    -- an extra SELECT predicate.
    for v_policy in
      select *
      from pg_policies p
      where p.schemaname = v_target.schema_name
        and p.tablename = v_target.table_name
        and p.cmd = 'ALL'
        and (
          'public' = any(p.roles)
          or 'anon' = any(p.roles)
          or 'authenticated' = any(p.roles)
        )
      order by p.policyname
    loop
      select string_agg(format('%I', role_name), ', ')
      into v_roles_sql
      from unnest(v_policy.roles) as role_name;

      v_check := coalesce(v_policy.with_check, v_policy.qual, 'true');
      v_insert_name := left(v_policy.policyname || ' insert', 63);
      v_update_name := left(v_policy.policyname || ' update', 63);
      v_delete_name := left(v_policy.policyname || ' delete', 63);

      execute format('drop policy %I on %I.%I',
        v_policy.policyname, v_target.schema_name, v_target.table_name);

      execute format('drop policy if exists %I on %I.%I',
        v_insert_name, v_target.schema_name, v_target.table_name);
      execute format('drop policy if exists %I on %I.%I',
        v_update_name, v_target.schema_name, v_target.table_name);
      execute format('drop policy if exists %I on %I.%I',
        v_delete_name, v_target.schema_name, v_target.table_name);

      execute format(
        'create policy %I on %I.%I for insert to %s with check (%s)',
        v_insert_name, v_target.schema_name, v_target.table_name, v_roles_sql, v_check
      );
      execute format(
        'create policy %I on %I.%I for update to %s using (%s) with check (%s)',
        v_update_name, v_target.schema_name, v_target.table_name, v_roles_sql,
        coalesce(v_policy.qual, 'true'), v_check
      );
      execute format(
        'create policy %I on %I.%I for delete to %s using (%s)',
        v_delete_name, v_target.schema_name, v_target.table_name, v_roles_sql,
        coalesce(v_policy.qual, 'true')
      );
    end loop;

    -- Remove the old SELECT policies that applied to browser roles. Their exact
    -- unions were captured above.
    for v_policy in
      select *
      from pg_policies p
      where p.schemaname = v_target.schema_name
        and p.tablename = v_target.table_name
        and p.cmd = 'SELECT'
        and (
          'public' = any(p.roles)
          or 'anon' = any(p.roles)
          or 'authenticated' = any(p.roles)
        )
      order by p.policyname
    loop
      execute format('drop policy %I on %I.%I',
        v_policy.policyname, v_target.schema_name, v_target.table_name);
    end loop;

    execute format('drop policy if exists %I on %I.%I',
      'solaris consolidated anon read', v_target.schema_name, v_target.table_name);
    execute format('drop policy if exists %I on %I.%I',
      'solaris consolidated authenticated read', v_target.schema_name, v_target.table_name);

    if v_anon_qual is not null then
      execute format(
        'create policy %I on %I.%I for select to anon using (%s)',
        'solaris consolidated anon read',
        v_target.schema_name, v_target.table_name, v_anon_qual
      );
    end if;

    if v_auth_qual is not null then
      execute format(
        'create policy %I on %I.%I for select to authenticated using (%s)',
        'solaris consolidated authenticated read',
        v_target.schema_name, v_target.table_name, v_auth_qual
      );
    end if;
  end loop;
end
$policy_consolidation$;

do $verify$
declare
  v_target record;
  v_count integer;
begin
  if to_regclass('public.contest_entities_country_id_idx') is null
     or to_regclass('public.country_hod_edition_claims_country_id_idx') is null
     or to_regclass('public.country_hod_edition_claims_edition_id_idx') is null
     or to_regclass('public.jury_votes_receiving_country_id_idx') is null
     or to_regclass('public.jury_votes_voter_country_id_idx') is null
     or to_regclass('public.jury_votes_voter_entity_id_idx') is null
     or to_regclass('public.participants_country_id_idx') is null
     or to_regclass('public.results_country_id_idx') is null
     or to_regclass('public.televote_votes_country_id_idx') is null
     or to_regclass('public.voters_contest_entity_id_idx') is null
     or to_regclass('public.voters_country_id_idx') is null then
    raise exception 'Expected high-volume FK indexes are missing';
  end if;

  if exists (select 1 from pg_namespace where nspname = 'migration_staging') then
    raise exception 'migration_staging still exists';
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'private.studio2_notice_deletion_audit'::regclass
      and contype = 'p'
  ) then
    raise exception 'private.studio2_notice_deletion_audit still has no primary key';
  end if;

  for v_target in
    select *
    from (values
      ('public','content_events'),('public','contest_entities'),('public','countries'),
      ('public','country_accounts'),('public','country_edition_identities'),
      ('public','country_hod_edition_claims'),('public','country_media'),
      ('public','country_profile_sections'),('public','country_profiles'),
      ('public','country_themes'),('public','editions'),('public','entries'),
      ('public','jury_ballot_submissions'),('public','jury_votes'),
      ('public','jury_voting_windows'),('public','participants'),
      ('public','prediction_rounds'),('public','results'),('public','shows'),
      ('public','submission_rounds'),('public','televote_votes'),('public','themes'),
      ('public','user_roles'),('public','voters'),
      ('televoting','combined_televote_component_results'),
      ('televoting','combined_televote_results'),('televoting','countries'),
      ('televoting','editions'),('televoting','round_countries'),
      ('televoting','round_entries'),('televoting','round_results'),
      ('televoting','rounds'),('televoting','televote_aggregation_participants'),
      ('televoting','televote_aggregations')
    ) as targets(schema_name, table_name)
  loop
    select count(*) into v_count
    from pg_policies p
    where p.schemaname = v_target.schema_name
      and p.tablename = v_target.table_name
      and p.cmd in ('SELECT','ALL')
      and ('public' = any(p.roles) or 'anon' = any(p.roles));

    if v_count > 1 then
      raise exception 'Multiple anon SELECT policies remain on %.%: %',
        v_target.schema_name, v_target.table_name, v_count;
    end if;

    select count(*) into v_count
    from pg_policies p
    where p.schemaname = v_target.schema_name
      and p.tablename = v_target.table_name
      and p.cmd in ('SELECT','ALL')
      and ('public' = any(p.roles) or 'authenticated' = any(p.roles));

    if v_count > 1 then
      raise exception 'Multiple authenticated SELECT policies remain on %.%: %',
        v_target.schema_name, v_target.table_name, v_count;
    end if;
  end loop;
end
$verify$;

notify pgrst, 'reload schema';

commit;
